// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/content/v1/oracle/oracle.proto

package oraclev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                                                // e.g., "post_view", "link_click"
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                        // 0 if anonymous
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                                                   // post_id or other resource
	Meta          map[string]string      `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外参数: device, referer
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventRequest) Reset() {
	*x = TrackEventRequest{}
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventRequest) ProtoMessage() {}

func (x *TrackEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventRequest.ProtoReflect.Descriptor instead.
func (*TrackEventRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_oracle_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *TrackEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TrackEventRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrackEventRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *TrackEventRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TrackEventRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type TrackEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventResponse) Reset() {
	*x = TrackEventResponse{}
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventResponse) ProtoMessage() {}

func (x *TrackEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventResponse.ProtoReflect.Descriptor instead.
func (*TrackEventResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_oracle_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *TrackEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetDashboardStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 时间范围
	StartTime     int64 `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp
	EndTime       int64 `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardStatsRequest) Reset() {
	*x = GetDashboardStatsRequest{}
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardStatsRequest) ProtoMessage() {}

func (x *GetDashboardStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_oracle_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *GetDashboardStatsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetDashboardStatsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetDashboardStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers       int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	ActiveUsersToday int64                  `protobuf:"varint,2,opt,name=active_users_today,json=activeUsersToday,proto3" json:"active_users_today,omitempty"`
	TotalPosts       int64                  `protobuf:"varint,3,opt,name=total_posts,json=totalPosts,proto3" json:"total_posts,omitempty"`
	TotalViews       int64                  `protobuf:"varint,4,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	// 简单的趋势图数据
	TrendData     map[string]int64 `protobuf:"bytes,5,rep,name=trend_data,json=trendData,proto3" json:"trend_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardStatsResponse) Reset() {
	*x = GetDashboardStatsResponse{}
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardStatsResponse) ProtoMessage() {}

func (x *GetDashboardStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_oracle_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *GetDashboardStatsResponse) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetActiveUsersToday() int64 {
	if x != nil {
		return x.ActiveUsersToday
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetTotalPosts() int64 {
	if x != nil {
		return x.TotalPosts
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetTotalViews() int64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetTrendData() map[string]int64 {
	if x != nil {
		return x.TrendData
	}
	return nil
}

type GetContentScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentScoreRequest) Reset() {
	*x = GetContentScoreRequest{}
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentScoreRequest) ProtoMessage() {}

func (x *GetContentScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentScoreRequest.ProtoReflect.Descriptor instead.
func (*GetContentScoreRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_oracle_oracle_proto_rawDescGZIP(), []int{4}
}

func (x *GetContentScoreRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetContentScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`            // 0-100
	Suggestions   []string               `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"` // e.g. "Title too short", "Lack of images"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentScoreResponse) Reset() {
	*x = GetContentScoreResponse{}
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentScoreResponse) ProtoMessage() {}

func (x *GetContentScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_oracle_oracle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentScoreResponse.ProtoReflect.Descriptor instead.
func (*GetContentScoreResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_oracle_oracle_proto_rawDescGZIP(), []int{5}
}

func (x *GetContentScoreResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GetContentScoreResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_api_content_v1_oracle_oracle_proto protoreflect.FileDescriptor

const file_api_content_v1_oracle_oracle_proto_rawDesc = "" +
	"\n" +
	"\"api/content/v1/oracle/oracle.proto\x12\x1abifrost.analysis.v1.oracle\x1a\x1cgoogle/api/annotations.proto\"\x89\x02\n" +
	"\x11TrackEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12K\n" +
	"\x04meta\x18\x04 \x03(\v27.bifrost.analysis.v1.oracle.TrackEventRequest.MetaEntryR\x04meta\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x12TrackEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"T\n" +
	"\x18GetDashboardStatsRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"\xcf\x02\n" +
	"\x19GetDashboardStatsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12,\n" +
	"\x12active_users_today\x18\x02 \x01(\x03R\x10activeUsersToday\x12\x1f\n" +
	"\vtotal_posts\x18\x03 \x01(\x03R\n" +
	"totalPosts\x12\x1f\n" +
	"\vtotal_views\x18\x04 \x01(\x03R\n" +
	"totalViews\x12c\n" +
	"\n" +
	"trend_data\x18\x05 \x03(\v2D.bifrost.analysis.v1.oracle.GetDashboardStatsResponse.TrendDataEntryR\ttrendData\x1a<\n" +
	"\x0eTrendDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"1\n" +
	"\x16GetContentScoreRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"Q\n" +
	"\x17GetContentScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12 \n" +
	"\vsuggestions\x18\x02 \x03(\tR\vsuggestions2\xbe\x03\n" +
	"\x0fAnalysisService\x12\x8b\x01\n" +
	"\n" +
	"TrackEvent\x12-.bifrost.analysis.v1.oracle.TrackEventRequest\x1a..bifrost.analysis.v1.oracle.TrackEventResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/analysis/events\x12\xa0\x01\n" +
	"\x11GetDashboardStats\x124.bifrost.analysis.v1.oracle.GetDashboardStatsRequest\x1a5.bifrost.analysis.v1.oracle.GetDashboardStatsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/analysis/dashboard\x12z\n" +
	"\x0fGetContentScore\x122.bifrost.analysis.v1.oracle.GetContentScoreRequest\x1a3.bifrost.analysis.v1.oracle.GetContentScoreResponseBAZ?github.com/gulugulu3399/bifrost/api/analysis/v1/oracle;oraclev1b\x06proto3"

var (
	file_api_content_v1_oracle_oracle_proto_rawDescOnce sync.Once
	file_api_content_v1_oracle_oracle_proto_rawDescData []byte
)

func file_api_content_v1_oracle_oracle_proto_rawDescGZIP() []byte {
	file_api_content_v1_oracle_oracle_proto_rawDescOnce.Do(func() {
		file_api_content_v1_oracle_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_content_v1_oracle_oracle_proto_rawDesc), len(file_api_content_v1_oracle_oracle_proto_rawDesc)))
	})
	return file_api_content_v1_oracle_oracle_proto_rawDescData
}

var file_api_content_v1_oracle_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_content_v1_oracle_oracle_proto_goTypes = []any{
	(*TrackEventRequest)(nil),         // 0: bifrost.analysis.v1.oracle.TrackEventRequest
	(*TrackEventResponse)(nil),        // 1: bifrost.analysis.v1.oracle.TrackEventResponse
	(*GetDashboardStatsRequest)(nil),  // 2: bifrost.analysis.v1.oracle.GetDashboardStatsRequest
	(*GetDashboardStatsResponse)(nil), // 3: bifrost.analysis.v1.oracle.GetDashboardStatsResponse
	(*GetContentScoreRequest)(nil),    // 4: bifrost.analysis.v1.oracle.GetContentScoreRequest
	(*GetContentScoreResponse)(nil),   // 5: bifrost.analysis.v1.oracle.GetContentScoreResponse
	nil,                               // 6: bifrost.analysis.v1.oracle.TrackEventRequest.MetaEntry
	nil,                               // 7: bifrost.analysis.v1.oracle.GetDashboardStatsResponse.TrendDataEntry
}
var file_api_content_v1_oracle_oracle_proto_depIdxs = []int32{
	6, // 0: bifrost.analysis.v1.oracle.TrackEventRequest.meta:type_name -> bifrost.analysis.v1.oracle.TrackEventRequest.MetaEntry
	7, // 1: bifrost.analysis.v1.oracle.GetDashboardStatsResponse.trend_data:type_name -> bifrost.analysis.v1.oracle.GetDashboardStatsResponse.TrendDataEntry
	0, // 2: bifrost.analysis.v1.oracle.AnalysisService.TrackEvent:input_type -> bifrost.analysis.v1.oracle.TrackEventRequest
	2, // 3: bifrost.analysis.v1.oracle.AnalysisService.GetDashboardStats:input_type -> bifrost.analysis.v1.oracle.GetDashboardStatsRequest
	4, // 4: bifrost.analysis.v1.oracle.AnalysisService.GetContentScore:input_type -> bifrost.analysis.v1.oracle.GetContentScoreRequest
	1, // 5: bifrost.analysis.v1.oracle.AnalysisService.TrackEvent:output_type -> bifrost.analysis.v1.oracle.TrackEventResponse
	3, // 6: bifrost.analysis.v1.oracle.AnalysisService.GetDashboardStats:output_type -> bifrost.analysis.v1.oracle.GetDashboardStatsResponse
	5, // 7: bifrost.analysis.v1.oracle.AnalysisService.GetContentScore:output_type -> bifrost.analysis.v1.oracle.GetContentScoreResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_content_v1_oracle_oracle_proto_init() }
func file_api_content_v1_oracle_oracle_proto_init() {
	if File_api_content_v1_oracle_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_content_v1_oracle_oracle_proto_rawDesc), len(file_api_content_v1_oracle_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_content_v1_oracle_oracle_proto_goTypes,
		DependencyIndexes: file_api_content_v1_oracle_oracle_proto_depIdxs,
		MessageInfos:      file_api_content_v1_oracle_oracle_proto_msgTypes,
	}.Build()
	File_api_content_v1_oracle_oracle_proto = out.File
	file_api_content_v1_oracle_oracle_proto_goTypes = nil
	file_api_content_v1_oracle_oracle_proto_depIdxs = nil
}
