// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/search/v1/mirror.proto

package searchv1

import (
	v1 "github.com/gulugulu3399/bifrost/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Query  string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // 搜索关键词
	Page   *v1.PageRequest        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`   // 分页
	Filter *SearchRequest_Filter  `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// [新增] 请求分面统计 (例如：我想知道搜索结果中，各分类下的文章数量)
	IncludeFacets bool `protobuf:"varint,4,opt,name=include_facets,json=includeFacets,proto3" json:"include_facets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_search_v1_mirror_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_mirror_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_search_v1_mirror_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *SearchRequest) GetFilter() *SearchRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchRequest) GetIncludeFacets() bool {
	if x != nil {
		return x.IncludeFacets
	}
	return false
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchResponse_Hit  `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	TotalHits     int32                  `protobuf:"varint,2,opt,name=total_hits,json=totalHits,proto3" json:"total_hits,omitempty"`
	TookMs        float32                `protobuf:"fixed32,3,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"` // 搜索引擎耗时
	Facets        *SearchResponse_Facets `protobuf:"bytes,4,opt,name=facets,proto3" json:"facets,omitempty"`                 // [新增] 返回统计信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_search_v1_mirror_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_mirror_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_search_v1_mirror_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetHits() []*SearchResponse_Hit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetTotalHits() int32 {
	if x != nil {
		return x.TotalHits
	}
	return 0
}

func (x *SearchResponse) GetTookMs() float32 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

func (x *SearchResponse) GetFacets() *SearchResponse_Facets {
	if x != nil {
		return x.Facets
	}
	return nil
}

type SuggestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // 用户当前输入的字符
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // 默认 5-10 条
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestRequest) Reset() {
	*x = SuggestRequest{}
	mi := &file_api_search_v1_mirror_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRequest) ProtoMessage() {}

func (x *SuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_mirror_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRequest.ProtoReflect.Descriptor instead.
func (*SuggestRequest) Descriptor() ([]byte, []int) {
	return file_api_search_v1_mirror_proto_rawDescGZIP(), []int{2}
}

func (x *SuggestRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *SuggestRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SuggestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"` // e.g. ["rust tutorial", "rust lifetime"]
	TookMs        float32                `protobuf:"fixed32,2,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestResponse) Reset() {
	*x = SuggestResponse{}
	mi := &file_api_search_v1_mirror_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResponse) ProtoMessage() {}

func (x *SuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_mirror_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResponse.ProtoReflect.Descriptor instead.
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return file_api_search_v1_mirror_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *SuggestResponse) GetTookMs() float32 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

type DebugIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         int64                  `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"` // 检查特定文档是否在索引中
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugIndexRequest) Reset() {
	*x = DebugIndexRequest{}
	mi := &file_api_search_v1_mirror_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugIndexRequest) ProtoMessage() {}

func (x *DebugIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_mirror_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugIndexRequest.ProtoReflect.Descriptor instead.
func (*DebugIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_search_v1_mirror_proto_rawDescGZIP(), []int{4}
}

func (x *DebugIndexRequest) GetDocId() int64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

type DebugIndexResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Indexed          bool                   `protobuf:"varint,1,opt,name=indexed,proto3" json:"indexed,omitempty"`
	StoredFieldsJson string                 `protobuf:"bytes,2,opt,name=stored_fields_json,json=storedFieldsJson,proto3" json:"stored_fields_json,omitempty"` // 返回索引中实际存储的内容
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DebugIndexResponse) Reset() {
	*x = DebugIndexResponse{}
	mi := &file_api_search_v1_mirror_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugIndexResponse) ProtoMessage() {}

func (x *DebugIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_mirror_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugIndexResponse.ProtoReflect.Descriptor instead.
func (*DebugIndexResponse) Descriptor() ([]byte, []int) {
	return file_api_search_v1_mirror_proto_rawDescGZIP(), []int{5}
}

func (x *DebugIndexResponse) GetIndexed() bool {
	if x != nil {
		return x.Indexed
	}
	return false
}

func (x *DebugIndexResponse) GetStoredFieldsJson() string {
	if x != nil {
		return x.StoredFieldsJson
	}
	return ""
}

// [优化] 结构化过滤器，替代原来的 repeated string
// Tantivy 处理这种结构化 Bool Query 速度极快
type SearchRequest_Filter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CategoryId     int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`               // 仅看某分类
	TagId          int64                  `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`                              // 仅看某标签
	AuthorId       int64                  `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`                     // 仅看某作者
	DateRangeStart int64                  `protobuf:"varint,4,opt,name=date_range_start,json=dateRangeStart,proto3" json:"date_range_start,omitempty"` // 时间范围筛选 (Unix Timestamp)
	DateRangeEnd   int64                  `protobuf:"varint,5,opt,name=date_range_end,json=dateRangeEnd,proto3" json:"date_range_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest_Filter) Reset() {
	*x = SearchRequest_Filter{}
	mi := &file_api_search_v1_mirror_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest_Filter) ProtoMessage() {}

func (x *SearchRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_mirror_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest_Filter.ProtoReflect.Descriptor instead.
func (*SearchRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_search_v1_mirror_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SearchRequest_Filter) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SearchRequest_Filter) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *SearchRequest_Filter) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *SearchRequest_Filter) GetDateRangeStart() int64 {
	if x != nil {
		return x.DateRangeStart
	}
	return 0
}

func (x *SearchRequest_Filter) GetDateRangeEnd() int64 {
	if x != nil {
		return x.DateRangeEnd
	}
	return 0
}

type SearchResponse_Hit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`        // 文章 ID (Snowflake)
	Score float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"` // BM25 相关性得分
	Title string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`   // 原标题
	Slug  string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`     // 用于前端路由跳转
	// 高亮片段 (HTML)
	// e.g. "Rust is <em>great</em> for systems..."
	HighlightTitle   string `protobuf:"bytes,5,opt,name=highlight_title,json=highlightTitle,proto3" json:"highlight_title,omitempty"`
	HighlightContent string `protobuf:"bytes,6,opt,name=highlight_content,json=highlightContent,proto3" json:"highlight_content,omitempty"`
	PublishedAt      int64  `protobuf:"varint,7,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // 用于结果展示的时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchResponse_Hit) Reset() {
	*x = SearchResponse_Hit{}
	mi := &file_api_search_v1_mirror_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse_Hit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Hit) ProtoMessage() {}

func (x *SearchResponse_Hit) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_mirror_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Hit.ProtoReflect.Descriptor instead.
func (*SearchResponse_Hit) Descriptor() ([]byte, []int) {
	return file_api_search_v1_mirror_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SearchResponse_Hit) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchResponse_Hit) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResponse_Hit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResponse_Hit) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SearchResponse_Hit) GetHighlightTitle() string {
	if x != nil {
		return x.HighlightTitle
	}
	return ""
}

func (x *SearchResponse_Hit) GetHighlightContent() string {
	if x != nil {
		return x.HighlightContent
	}
	return ""
}

func (x *SearchResponse_Hit) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

// 分面统计项
type SearchResponse_FacetBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`  // e.g. "Technology" or CategoryID "1001"
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 命中数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse_FacetBucket) Reset() {
	*x = SearchResponse_FacetBucket{}
	mi := &file_api_search_v1_mirror_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse_FacetBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_FacetBucket) ProtoMessage() {}

func (x *SearchResponse_FacetBucket) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_mirror_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_FacetBucket.ProtoReflect.Descriptor instead.
func (*SearchResponse_FacetBucket) Descriptor() ([]byte, []int) {
	return file_api_search_v1_mirror_proto_rawDescGZIP(), []int{1, 1}
}

func (x *SearchResponse_FacetBucket) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SearchResponse_FacetBucket) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchResponse_Facets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    map[string]int64       `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key: category_id, value: count
	Tags          map[string]int64       `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`             // key: tag_id, value: count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse_Facets) Reset() {
	*x = SearchResponse_Facets{}
	mi := &file_api_search_v1_mirror_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse_Facets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Facets) ProtoMessage() {}

func (x *SearchResponse_Facets) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_mirror_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Facets.ProtoReflect.Descriptor instead.
func (*SearchResponse_Facets) Descriptor() ([]byte, []int) {
	return file_api_search_v1_mirror_proto_rawDescGZIP(), []int{1, 2}
}

func (x *SearchResponse_Facets) GetCategories() map[string]int64 {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *SearchResponse_Facets) GetTags() map[string]int64 {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_api_search_v1_mirror_proto protoreflect.FileDescriptor

const file_api_search_v1_mirror_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/search/v1/mirror.proto\x12\x11bifrost.search.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1aapi/common/v1/common.proto\"\xf1\x02\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x122\n" +
	"\x04page\x18\x02 \x01(\v2\x1e.bifrost.common.v1.PageRequestR\x04page\x12?\n" +
	"\x06filter\x18\x03 \x01(\v2'.bifrost.search.v1.SearchRequest.FilterR\x06filter\x12%\n" +
	"\x0einclude_facets\x18\x04 \x01(\bR\rincludeFacets\x1a\xad\x01\n" +
	"\x06Filter\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x03R\x05tagId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x03R\bauthorId\x12(\n" +
	"\x10date_range_start\x18\x04 \x01(\x03R\x0edateRangeStart\x12$\n" +
	"\x0edate_range_end\x18\x05 \x01(\x03R\fdateRangeEnd\"\xf6\x05\n" +
	"\x0eSearchResponse\x129\n" +
	"\x04hits\x18\x01 \x03(\v2%.bifrost.search.v1.SearchResponse.HitR\x04hits\x12\x1d\n" +
	"\n" +
	"total_hits\x18\x02 \x01(\x05R\ttotalHits\x12\x17\n" +
	"\atook_ms\x18\x03 \x01(\x02R\x06tookMs\x12@\n" +
	"\x06facets\x18\x04 \x01(\v2(.bifrost.search.v1.SearchResponse.FacetsR\x06facets\x1a\xce\x01\n" +
	"\x03Hit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12'\n" +
	"\x0fhighlight_title\x18\x05 \x01(\tR\x0ehighlightTitle\x12+\n" +
	"\x11highlight_content\x18\x06 \x01(\tR\x10highlightContent\x12!\n" +
	"\fpublished_at\x18\a \x01(\x03R\vpublishedAt\x1a9\n" +
	"\vFacetBucket\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x1a\xa2\x02\n" +
	"\x06Facets\x12X\n" +
	"\n" +
	"categories\x18\x01 \x03(\v28.bifrost.search.v1.SearchResponse.Facets.CategoriesEntryR\n" +
	"categories\x12F\n" +
	"\x04tags\x18\x02 \x03(\v22.bifrost.search.v1.SearchResponse.Facets.TagsEntryR\x04tags\x1a=\n" +
	"\x0fCategoriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\">\n" +
	"\x0eSuggestRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"L\n" +
	"\x0fSuggestResponse\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestions\x12\x17\n" +
	"\atook_ms\x18\x02 \x01(\x02R\x06tookMs\"*\n" +
	"\x11DebugIndexRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x03R\x05docId\"\\\n" +
	"\x12DebugIndexResponse\x12\x18\n" +
	"\aindexed\x18\x01 \x01(\bR\aindexed\x12,\n" +
	"\x12stored_fields_json\x18\x02 \x01(\tR\x10storedFieldsJson2\xbb\x02\n" +
	"\rMirrorService\x12a\n" +
	"\x06Search\x12 .bifrost.search.v1.SearchRequest\x1a!.bifrost.search.v1.SearchResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/search\x12l\n" +
	"\aSuggest\x12!.bifrost.search.v1.SuggestRequest\x1a\".bifrost.search.v1.SuggestResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/search/suggest\x12Y\n" +
	"\n" +
	"DebugIndex\x12$.bifrost.search.v1.DebugIndexRequest\x1a%.bifrost.search.v1.DebugIndexResponseB8Z6github.com/gulugulu3399/bifrost/api/search/v1;searchv1b\x06proto3"

var (
	file_api_search_v1_mirror_proto_rawDescOnce sync.Once
	file_api_search_v1_mirror_proto_rawDescData []byte
)

func file_api_search_v1_mirror_proto_rawDescGZIP() []byte {
	file_api_search_v1_mirror_proto_rawDescOnce.Do(func() {
		file_api_search_v1_mirror_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_search_v1_mirror_proto_rawDesc), len(file_api_search_v1_mirror_proto_rawDesc)))
	})
	return file_api_search_v1_mirror_proto_rawDescData
}

var file_api_search_v1_mirror_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_search_v1_mirror_proto_goTypes = []any{
	(*SearchRequest)(nil),              // 0: bifrost.search.v1.SearchRequest
	(*SearchResponse)(nil),             // 1: bifrost.search.v1.SearchResponse
	(*SuggestRequest)(nil),             // 2: bifrost.search.v1.SuggestRequest
	(*SuggestResponse)(nil),            // 3: bifrost.search.v1.SuggestResponse
	(*DebugIndexRequest)(nil),          // 4: bifrost.search.v1.DebugIndexRequest
	(*DebugIndexResponse)(nil),         // 5: bifrost.search.v1.DebugIndexResponse
	(*SearchRequest_Filter)(nil),       // 6: bifrost.search.v1.SearchRequest.Filter
	(*SearchResponse_Hit)(nil),         // 7: bifrost.search.v1.SearchResponse.Hit
	(*SearchResponse_FacetBucket)(nil), // 8: bifrost.search.v1.SearchResponse.FacetBucket
	(*SearchResponse_Facets)(nil),      // 9: bifrost.search.v1.SearchResponse.Facets
	nil,                                // 10: bifrost.search.v1.SearchResponse.Facets.CategoriesEntry
	nil,                                // 11: bifrost.search.v1.SearchResponse.Facets.TagsEntry
	(*v1.PageRequest)(nil),             // 12: bifrost.common.v1.PageRequest
}
var file_api_search_v1_mirror_proto_depIdxs = []int32{
	12, // 0: bifrost.search.v1.SearchRequest.page:type_name -> bifrost.common.v1.PageRequest
	6,  // 1: bifrost.search.v1.SearchRequest.filter:type_name -> bifrost.search.v1.SearchRequest.Filter
	7,  // 2: bifrost.search.v1.SearchResponse.hits:type_name -> bifrost.search.v1.SearchResponse.Hit
	9,  // 3: bifrost.search.v1.SearchResponse.facets:type_name -> bifrost.search.v1.SearchResponse.Facets
	10, // 4: bifrost.search.v1.SearchResponse.Facets.categories:type_name -> bifrost.search.v1.SearchResponse.Facets.CategoriesEntry
	11, // 5: bifrost.search.v1.SearchResponse.Facets.tags:type_name -> bifrost.search.v1.SearchResponse.Facets.TagsEntry
	0,  // 6: bifrost.search.v1.MirrorService.Search:input_type -> bifrost.search.v1.SearchRequest
	2,  // 7: bifrost.search.v1.MirrorService.Suggest:input_type -> bifrost.search.v1.SuggestRequest
	4,  // 8: bifrost.search.v1.MirrorService.DebugIndex:input_type -> bifrost.search.v1.DebugIndexRequest
	1,  // 9: bifrost.search.v1.MirrorService.Search:output_type -> bifrost.search.v1.SearchResponse
	3,  // 10: bifrost.search.v1.MirrorService.Suggest:output_type -> bifrost.search.v1.SuggestResponse
	5,  // 11: bifrost.search.v1.MirrorService.DebugIndex:output_type -> bifrost.search.v1.DebugIndexResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_search_v1_mirror_proto_init() }
func file_api_search_v1_mirror_proto_init() {
	if File_api_search_v1_mirror_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_search_v1_mirror_proto_rawDesc), len(file_api_search_v1_mirror_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_search_v1_mirror_proto_goTypes,
		DependencyIndexes: file_api_search_v1_mirror_proto_depIdxs,
		MessageInfos:      file_api_search_v1_mirror_proto_msgTypes,
	}.Build()
	File_api_search_v1_mirror_proto = out.File
	file_api_search_v1_mirror_proto_goTypes = nil
	file_api_search_v1_mirror_proto_depIdxs = nil
}
