// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: api/search/v1/mirror.proto

package searchv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MirrorService_Search_FullMethodName     = "/bifrost.search.v1.MirrorService/Search"
	MirrorService_Suggest_FullMethodName    = "/bifrost.search.v1.MirrorService/Suggest"
	MirrorService_DebugIndex_FullMethodName = "/bifrost.search.v1.MirrorService/DebugIndex"
)

// MirrorServiceClient is the client API for MirrorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Mirror Service: Rust 实现的高性能全文检索引擎
type MirrorServiceClient interface {
	// 全文搜索 (支持高亮、过滤、分面统计)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// [新增] 搜索建议/自动补全 (Search-as-you-type)
	// 用于搜索框下拉提示，极低延迟 (<20ms)
	Suggest(ctx context.Context, in *SuggestRequest, opts ...grpc.CallOption) (*SuggestResponse, error)
	// [新增] 索引管理接口 (运维用，通常不暴露给公网)
	// 用于手动触发重新索引或调试
	DebugIndex(ctx context.Context, in *DebugIndexRequest, opts ...grpc.CallOption) (*DebugIndexResponse, error)
}

type mirrorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMirrorServiceClient(cc grpc.ClientConnInterface) MirrorServiceClient {
	return &mirrorServiceClient{cc}
}

func (c *mirrorServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MirrorService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mirrorServiceClient) Suggest(ctx context.Context, in *SuggestRequest, opts ...grpc.CallOption) (*SuggestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestResponse)
	err := c.cc.Invoke(ctx, MirrorService_Suggest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mirrorServiceClient) DebugIndex(ctx context.Context, in *DebugIndexRequest, opts ...grpc.CallOption) (*DebugIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebugIndexResponse)
	err := c.cc.Invoke(ctx, MirrorService_DebugIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MirrorServiceServer is the server API for MirrorService service.
// All implementations must embed UnimplementedMirrorServiceServer
// for forward compatibility.
//
// Mirror Service: Rust 实现的高性能全文检索引擎
type MirrorServiceServer interface {
	// 全文搜索 (支持高亮、过滤、分面统计)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// [新增] 搜索建议/自动补全 (Search-as-you-type)
	// 用于搜索框下拉提示，极低延迟 (<20ms)
	Suggest(context.Context, *SuggestRequest) (*SuggestResponse, error)
	// [新增] 索引管理接口 (运维用，通常不暴露给公网)
	// 用于手动触发重新索引或调试
	DebugIndex(context.Context, *DebugIndexRequest) (*DebugIndexResponse, error)
	mustEmbedUnimplementedMirrorServiceServer()
}

// UnimplementedMirrorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMirrorServiceServer struct{}

func (UnimplementedMirrorServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMirrorServiceServer) Suggest(context.Context, *SuggestRequest) (*SuggestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Suggest not implemented")
}
func (UnimplementedMirrorServiceServer) DebugIndex(context.Context, *DebugIndexRequest) (*DebugIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DebugIndex not implemented")
}
func (UnimplementedMirrorServiceServer) mustEmbedUnimplementedMirrorServiceServer() {}
func (UnimplementedMirrorServiceServer) testEmbeddedByValue()                       {}

// UnsafeMirrorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MirrorServiceServer will
// result in compilation errors.
type UnsafeMirrorServiceServer interface {
	mustEmbedUnimplementedMirrorServiceServer()
}

func RegisterMirrorServiceServer(s grpc.ServiceRegistrar, srv MirrorServiceServer) {
	// If the following call panics, it indicates UnimplementedMirrorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MirrorService_ServiceDesc, srv)
}

func _MirrorService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MirrorServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MirrorService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MirrorServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MirrorService_Suggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MirrorServiceServer).Suggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MirrorService_Suggest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MirrorServiceServer).Suggest(ctx, req.(*SuggestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MirrorService_DebugIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MirrorServiceServer).DebugIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MirrorService_DebugIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MirrorServiceServer).DebugIndex(ctx, req.(*DebugIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MirrorService_ServiceDesc is the grpc.ServiceDesc for MirrorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MirrorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bifrost.search.v1.MirrorService",
	HandlerType: (*MirrorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _MirrorService_Search_Handler,
		},
		{
			MethodName: "Suggest",
			Handler:    _MirrorService_Suggest_Handler,
		},
		{
			MethodName: "DebugIndex",
			Handler:    _MirrorService_DebugIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/search/v1/mirror.proto",
}
