// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/content/v1/beacon/beacon.proto

package beaconv1

import (
	v1 "github.com/gulugulu3399/bifrost/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [文章摘要] 用于列表页，无 HTML/Markdown
type PostSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	CoverImageKey string                 `protobuf:"bytes,5,opt,name=cover_image_key,json=coverImageKey,proto3" json:"cover_image_key,omitempty"`
	// 统计
	ViewCount    int32 `protobuf:"varint,6,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount    int32 `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount int32 `protobuf:"varint,8,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	// 核心元数据
	PublishedAt int64 `protobuf:"varint,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // Unix Timestamp
	// 内嵌简易对象 (减少前端请求数)
	Author        *AuthorInfo   `protobuf:"bytes,10,opt,name=author,proto3" json:"author,omitempty"`
	Category      *CategoryItem `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []*TagItem    `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostSummary) Reset() {
	*x = PostSummary{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSummary) ProtoMessage() {}

func (x *PostSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSummary.ProtoReflect.Descriptor instead.
func (*PostSummary) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{0}
}

func (x *PostSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostSummary) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PostSummary) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PostSummary) GetCoverImageKey() string {
	if x != nil {
		return x.CoverImageKey
	}
	return ""
}

func (x *PostSummary) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *PostSummary) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostSummary) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *PostSummary) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *PostSummary) GetAuthor() *AuthorInfo {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *PostSummary) GetCategory() *CategoryItem {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *PostSummary) GetTags() []*TagItem {
	if x != nil {
		return x.Tags
	}
	return nil
}

// [文章详情] 包含 HTML
type PostDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	CoverImageKey string                 `protobuf:"bytes,5,opt,name=cover_image_key,json=coverImageKey,proto3" json:"cover_image_key,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,6,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"` // 渲染后的 HTML
	TocJson       string                 `protobuf:"bytes,7,opt,name=toc_json,json=tocJson,proto3" json:"toc_json,omitempty"`    // 目录结构
	ViewCount     int32                  `protobuf:"varint,8,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount     int32                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Author        *AuthorInfo            `protobuf:"bytes,12,opt,name=author,proto3" json:"author,omitempty"`
	Category      *CategoryItem          `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []*TagItem             `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	// 临近文章导航
	PrevPostId    int64  `protobuf:"varint,15,opt,name=prev_post_id,json=prevPostId,proto3" json:"prev_post_id,omitempty"`
	PrevPostTitle string `protobuf:"bytes,16,opt,name=prev_post_title,json=prevPostTitle,proto3" json:"prev_post_title,omitempty"`
	PrevPostSlug  string `protobuf:"bytes,17,opt,name=prev_post_slug,json=prevPostSlug,proto3" json:"prev_post_slug,omitempty"`
	NextPostId    int64  `protobuf:"varint,18,opt,name=next_post_id,json=nextPostId,proto3" json:"next_post_id,omitempty"`
	NextPostTitle string `protobuf:"bytes,19,opt,name=next_post_title,json=nextPostTitle,proto3" json:"next_post_title,omitempty"`
	NextPostSlug  string `protobuf:"bytes,20,opt,name=next_post_slug,json=nextPostSlug,proto3" json:"next_post_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDetail) Reset() {
	*x = PostDetail{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDetail) ProtoMessage() {}

func (x *PostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDetail.ProtoReflect.Descriptor instead.
func (*PostDetail) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{1}
}

func (x *PostDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostDetail) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PostDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PostDetail) GetCoverImageKey() string {
	if x != nil {
		return x.CoverImageKey
	}
	return ""
}

func (x *PostDetail) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *PostDetail) GetTocJson() string {
	if x != nil {
		return x.TocJson
	}
	return ""
}

func (x *PostDetail) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *PostDetail) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostDetail) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *PostDetail) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *PostDetail) GetAuthor() *AuthorInfo {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *PostDetail) GetCategory() *CategoryItem {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *PostDetail) GetTags() []*TagItem {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PostDetail) GetPrevPostId() int64 {
	if x != nil {
		return x.PrevPostId
	}
	return 0
}

func (x *PostDetail) GetPrevPostTitle() string {
	if x != nil {
		return x.PrevPostTitle
	}
	return ""
}

func (x *PostDetail) GetPrevPostSlug() string {
	if x != nil {
		return x.PrevPostSlug
	}
	return ""
}

func (x *PostDetail) GetNextPostId() int64 {
	if x != nil {
		return x.NextPostId
	}
	return 0
}

func (x *PostDetail) GetNextPostTitle() string {
	if x != nil {
		return x.NextPostTitle
	}
	return ""
}

func (x *PostDetail) GetNextPostSlug() string {
	if x != nil {
		return x.NextPostSlug
	}
	return ""
}

// [用户资料] 公开的主页信息 (不同于 AuthorInfo)
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarKey     string                 `protobuf:"bytes,4,opt,name=avatar_key,json=avatarKey,proto3" json:"avatar_key,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	PostCount     int32                  `protobuf:"varint,6,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"` // 发布的文章数
	RegisteredAt  int64                  `protobuf:"varint,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetAvatarKey() string {
	if x != nil {
		return x.AvatarKey
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetPostCount() int32 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

func (x *UserProfile) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

// [作者简略] 用于文章/评论列表的内嵌
type AuthorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 显示名
	AvatarKey     string                 `protobuf:"bytes,3,opt,name=avatar_key,json=avatarKey,proto3" json:"avatar_key,omitempty"` // 列表页通常不需要 bio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorInfo) Reset() {
	*x = AuthorInfo{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorInfo) ProtoMessage() {}

func (x *AuthorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorInfo.ProtoReflect.Descriptor instead.
func (*AuthorInfo) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthorInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AuthorInfo) GetAvatarKey() string {
	if x != nil {
		return x.AvatarKey
	}
	return ""
}

// [分类] 纯粹的展示对象
type CategoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PostCount     int32                  `protobuf:"varint,5,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryItem) Reset() {
	*x = CategoryItem{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryItem) ProtoMessage() {}

func (x *CategoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryItem.ProtoReflect.Descriptor instead.
func (*CategoryItem) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategoryItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryItem) GetPostCount() int32 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

// [标签] 纯粹的展示对象
type TagItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	PostCount     int32                  `protobuf:"varint,4,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagItem) Reset() {
	*x = TagItem{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagItem) ProtoMessage() {}

func (x *TagItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagItem.ProtoReflect.Descriptor instead.
func (*TagItem) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{5}
}

func (x *TagItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *TagItem) GetPostCount() int32 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

// [评论]
type CommentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	User          *AuthorInfo            `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                          // 评论人
	ParentId      int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 回复 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentItem) Reset() {
	*x = CommentItem{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentItem) ProtoMessage() {}

func (x *CommentItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentItem.ProtoReflect.Descriptor instead.
func (*CommentItem) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{6}
}

func (x *CommentItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CommentItem) GetUser() *AuthorInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CommentItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

// Post
type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlugOrId      string                 `protobuf:"bytes,1,opt,name=slug_or_id,json=slugOrId,proto3" json:"slug_or_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostRequest) GetSlugOrId() string {
	if x != nil {
		return x.SlugOrId
	}
	return ""
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostDetail            `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{8}
}

func (x *GetPostResponse) GetPost() *PostDetail {
	if x != nil {
		return x.Post
	}
	return nil
}

type ListPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TagId         int64                  `protobuf:"varint,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest) Reset() {
	*x = ListPostsRequest{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest) ProtoMessage() {}

func (x *ListPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest.ProtoReflect.Descriptor instead.
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{9}
}

func (x *ListPostsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListPostsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListPostsRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *ListPostsRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type ListPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostSummary         `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsResponse) Reset() {
	*x = ListPostsResponse{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsResponse) ProtoMessage() {}

func (x *ListPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsResponse.ProtoReflect.Descriptor instead.
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{10}
}

func (x *ListPostsResponse) GetPosts() []*PostSummary {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListPostsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// Comment
type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{11}
}

func (x *ListCommentsRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *ListCommentsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentItem         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{12}
}

func (x *ListCommentsResponse) GetComments() []*CommentItem {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// User
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProfile           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserResponse) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

// Meta
type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{15}
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryItem        `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{16}
}

func (x *ListCategoriesResponse) GetCategories() []*CategoryItem {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{17}
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagItem             `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_beacon_beacon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_beacon_beacon_proto_rawDescGZIP(), []int{18}
}

func (x *ListTagsResponse) GetTags() []*TagItem {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_api_content_v1_beacon_beacon_proto protoreflect.FileDescriptor

const file_api_content_v1_beacon_beacon_proto_rawDesc = "" +
	"\n" +
	"\"api/content/v1/beacon/beacon.proto\x12\x19bifrost.content.v1.beacon\x1a\x1cgoogle/api/annotations.proto\x1a\x1aapi/common/v1/common.proto\"\xcb\x03\n" +
	"\vPostSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12&\n" +
	"\x0fcover_image_key\x18\x05 \x01(\tR\rcoverImageKey\x12\x1d\n" +
	"\n" +
	"view_count\x18\x06 \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x05R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\b \x01(\x05R\fcommentCount\x12!\n" +
	"\fpublished_at\x18\t \x01(\x03R\vpublishedAt\x12=\n" +
	"\x06author\x18\n" +
	" \x01(\v2%.bifrost.content.v1.beacon.AuthorInfoR\x06author\x12C\n" +
	"\bcategory\x18\v \x01(\v2'.bifrost.content.v1.beacon.CategoryItemR\bcategory\x126\n" +
	"\x04tags\x18\f \x03(\v2\".bifrost.content.v1.beacon.TagItemR\x04tags\"\xdc\x05\n" +
	"\n" +
	"PostDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12&\n" +
	"\x0fcover_image_key\x18\x05 \x01(\tR\rcoverImageKey\x12\x1b\n" +
	"\thtml_body\x18\x06 \x01(\tR\bhtmlBody\x12\x19\n" +
	"\btoc_json\x18\a \x01(\tR\atocJson\x12\x1d\n" +
	"\n" +
	"view_count\x18\b \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x05R\tlikeCount\x12!\n" +
	"\fpublished_at\x18\n" +
	" \x01(\x03R\vpublishedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12=\n" +
	"\x06author\x18\f \x01(\v2%.bifrost.content.v1.beacon.AuthorInfoR\x06author\x12C\n" +
	"\bcategory\x18\r \x01(\v2'.bifrost.content.v1.beacon.CategoryItemR\bcategory\x126\n" +
	"\x04tags\x18\x0e \x03(\v2\".bifrost.content.v1.beacon.TagItemR\x04tags\x12 \n" +
	"\fprev_post_id\x18\x0f \x01(\x03R\n" +
	"prevPostId\x12&\n" +
	"\x0fprev_post_title\x18\x10 \x01(\tR\rprevPostTitle\x12$\n" +
	"\x0eprev_post_slug\x18\x11 \x01(\tR\fprevPostSlug\x12 \n" +
	"\fnext_post_id\x18\x12 \x01(\x03R\n" +
	"nextPostId\x12&\n" +
	"\x0fnext_post_title\x18\x13 \x01(\tR\rnextPostTitle\x12$\n" +
	"\x0enext_post_slug\x18\x14 \x01(\tR\fnextPostSlug\"\xca\x01\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_key\x18\x04 \x01(\tR\tavatarKey\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"post_count\x18\x06 \x01(\x05R\tpostCount\x12#\n" +
	"\rregistered_at\x18\a \x01(\x03R\fregisteredAt\"W\n" +
	"\n" +
	"AuthorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_key\x18\x03 \x01(\tR\tavatarKey\"\x87\x01\n" +
	"\fCategoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"post_count\x18\x05 \x01(\x05R\tpostCount\"`\n" +
	"\aTagItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1d\n" +
	"\n" +
	"post_count\x18\x04 \x01(\x05R\tpostCount\"\xae\x01\n" +
	"\vCommentItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x129\n" +
	"\x04user\x18\x04 \x01(\v2%.bifrost.content.v1.beacon.AuthorInfoR\x04user\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\".\n" +
	"\x0eGetPostRequest\x12\x1c\n" +
	"\n" +
	"slug_or_id\x18\x01 \x01(\tR\bslugOrId\"L\n" +
	"\x0fGetPostResponse\x129\n" +
	"\x04post\x18\x01 \x01(\v2%.bifrost.content.v1.beacon.PostDetailR\x04post\"\x9b\x01\n" +
	"\x10ListPostsRequest\x122\n" +
	"\x04page\x18\x01 \x01(\v2\x1e.bifrost.common.v1.PageRequestR\x04page\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x15\n" +
	"\x06tag_id\x18\x03 \x01(\x03R\x05tagId\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\"\x86\x01\n" +
	"\x11ListPostsResponse\x12<\n" +
	"\x05posts\x18\x01 \x03(\v2&.bifrost.content.v1.beacon.PostSummaryR\x05posts\x123\n" +
	"\x04page\x18\x02 \x01(\v2\x1f.bifrost.common.v1.PageResponseR\x04page\"b\n" +
	"\x13ListCommentsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x122\n" +
	"\x04page\x18\x02 \x01(\v2\x1e.bifrost.common.v1.PageRequestR\x04page\"\x8f\x01\n" +
	"\x14ListCommentsResponse\x12B\n" +
	"\bcomments\x18\x01 \x03(\v2&.bifrost.content.v1.beacon.CommentItemR\bcomments\x123\n" +
	"\x04page\x18\x02 \x01(\v2\x1f.bifrost.common.v1.PageResponseR\x04page\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"M\n" +
	"\x0fGetUserResponse\x12:\n" +
	"\x04user\x18\x01 \x01(\v2&.bifrost.content.v1.beacon.UserProfileR\x04user\"\x17\n" +
	"\x15ListCategoriesRequest\"a\n" +
	"\x16ListCategoriesResponse\x12G\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2'.bifrost.content.v1.beacon.CategoryItemR\n" +
	"categories\"\x11\n" +
	"\x0fListTagsRequest\"J\n" +
	"\x10ListTagsResponse\x126\n" +
	"\x04tags\x18\x01 \x03(\v2\".bifrost.content.v1.beacon.TagItemR\x04tags2\xab\x06\n" +
	"\rBeaconService\x12\x80\x01\n" +
	"\aGetPost\x12).bifrost.content.v1.beacon.GetPostRequest\x1a*.bifrost.content.v1.beacon.GetPostResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/posts/{slug_or_id}\x12y\n" +
	"\tListPosts\x12+.bifrost.content.v1.beacon.ListPostsRequest\x1a,.bifrost.content.v1.beacon.ListPostsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/posts\x12\x95\x01\n" +
	"\fListComments\x12..bifrost.content.v1.beacon.ListCommentsRequest\x1a/.bifrost.content.v1.beacon.ListCommentsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/posts/{post_id}/comments\x12}\n" +
	"\aGetUser\x12).bifrost.content.v1.beacon.GetUserRequest\x1a*.bifrost.content.v1.beacon.GetUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/{user_id}\x12\x8d\x01\n" +
	"\x0eListCategories\x120.bifrost.content.v1.beacon.ListCategoriesRequest\x1a1.bifrost.content.v1.beacon.ListCategoriesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/categories\x12u\n" +
	"\bListTags\x12*.bifrost.content.v1.beacon.ListTagsRequest\x1a+.bifrost.content.v1.beacon.ListTagsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/tagsB@Z>github.com/gulugulu3399/bifrost/api/content/v1/beacon;beaconv1b\x06proto3"

var (
	file_api_content_v1_beacon_beacon_proto_rawDescOnce sync.Once
	file_api_content_v1_beacon_beacon_proto_rawDescData []byte
)

func file_api_content_v1_beacon_beacon_proto_rawDescGZIP() []byte {
	file_api_content_v1_beacon_beacon_proto_rawDescOnce.Do(func() {
		file_api_content_v1_beacon_beacon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_content_v1_beacon_beacon_proto_rawDesc), len(file_api_content_v1_beacon_beacon_proto_rawDesc)))
	})
	return file_api_content_v1_beacon_beacon_proto_rawDescData
}

var file_api_content_v1_beacon_beacon_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_content_v1_beacon_beacon_proto_goTypes = []any{
	(*PostSummary)(nil),            // 0: bifrost.content.v1.beacon.PostSummary
	(*PostDetail)(nil),             // 1: bifrost.content.v1.beacon.PostDetail
	(*UserProfile)(nil),            // 2: bifrost.content.v1.beacon.UserProfile
	(*AuthorInfo)(nil),             // 3: bifrost.content.v1.beacon.AuthorInfo
	(*CategoryItem)(nil),           // 4: bifrost.content.v1.beacon.CategoryItem
	(*TagItem)(nil),                // 5: bifrost.content.v1.beacon.TagItem
	(*CommentItem)(nil),            // 6: bifrost.content.v1.beacon.CommentItem
	(*GetPostRequest)(nil),         // 7: bifrost.content.v1.beacon.GetPostRequest
	(*GetPostResponse)(nil),        // 8: bifrost.content.v1.beacon.GetPostResponse
	(*ListPostsRequest)(nil),       // 9: bifrost.content.v1.beacon.ListPostsRequest
	(*ListPostsResponse)(nil),      // 10: bifrost.content.v1.beacon.ListPostsResponse
	(*ListCommentsRequest)(nil),    // 11: bifrost.content.v1.beacon.ListCommentsRequest
	(*ListCommentsResponse)(nil),   // 12: bifrost.content.v1.beacon.ListCommentsResponse
	(*GetUserRequest)(nil),         // 13: bifrost.content.v1.beacon.GetUserRequest
	(*GetUserResponse)(nil),        // 14: bifrost.content.v1.beacon.GetUserResponse
	(*ListCategoriesRequest)(nil),  // 15: bifrost.content.v1.beacon.ListCategoriesRequest
	(*ListCategoriesResponse)(nil), // 16: bifrost.content.v1.beacon.ListCategoriesResponse
	(*ListTagsRequest)(nil),        // 17: bifrost.content.v1.beacon.ListTagsRequest
	(*ListTagsResponse)(nil),       // 18: bifrost.content.v1.beacon.ListTagsResponse
	(*v1.PageRequest)(nil),         // 19: bifrost.common.v1.PageRequest
	(*v1.PageResponse)(nil),        // 20: bifrost.common.v1.PageResponse
}
var file_api_content_v1_beacon_beacon_proto_depIdxs = []int32{
	3,  // 0: bifrost.content.v1.beacon.PostSummary.author:type_name -> bifrost.content.v1.beacon.AuthorInfo
	4,  // 1: bifrost.content.v1.beacon.PostSummary.category:type_name -> bifrost.content.v1.beacon.CategoryItem
	5,  // 2: bifrost.content.v1.beacon.PostSummary.tags:type_name -> bifrost.content.v1.beacon.TagItem
	3,  // 3: bifrost.content.v1.beacon.PostDetail.author:type_name -> bifrost.content.v1.beacon.AuthorInfo
	4,  // 4: bifrost.content.v1.beacon.PostDetail.category:type_name -> bifrost.content.v1.beacon.CategoryItem
	5,  // 5: bifrost.content.v1.beacon.PostDetail.tags:type_name -> bifrost.content.v1.beacon.TagItem
	3,  // 6: bifrost.content.v1.beacon.CommentItem.user:type_name -> bifrost.content.v1.beacon.AuthorInfo
	1,  // 7: bifrost.content.v1.beacon.GetPostResponse.post:type_name -> bifrost.content.v1.beacon.PostDetail
	19, // 8: bifrost.content.v1.beacon.ListPostsRequest.page:type_name -> bifrost.common.v1.PageRequest
	0,  // 9: bifrost.content.v1.beacon.ListPostsResponse.posts:type_name -> bifrost.content.v1.beacon.PostSummary
	20, // 10: bifrost.content.v1.beacon.ListPostsResponse.page:type_name -> bifrost.common.v1.PageResponse
	19, // 11: bifrost.content.v1.beacon.ListCommentsRequest.page:type_name -> bifrost.common.v1.PageRequest
	6,  // 12: bifrost.content.v1.beacon.ListCommentsResponse.comments:type_name -> bifrost.content.v1.beacon.CommentItem
	20, // 13: bifrost.content.v1.beacon.ListCommentsResponse.page:type_name -> bifrost.common.v1.PageResponse
	2,  // 14: bifrost.content.v1.beacon.GetUserResponse.user:type_name -> bifrost.content.v1.beacon.UserProfile
	4,  // 15: bifrost.content.v1.beacon.ListCategoriesResponse.categories:type_name -> bifrost.content.v1.beacon.CategoryItem
	5,  // 16: bifrost.content.v1.beacon.ListTagsResponse.tags:type_name -> bifrost.content.v1.beacon.TagItem
	7,  // 17: bifrost.content.v1.beacon.BeaconService.GetPost:input_type -> bifrost.content.v1.beacon.GetPostRequest
	9,  // 18: bifrost.content.v1.beacon.BeaconService.ListPosts:input_type -> bifrost.content.v1.beacon.ListPostsRequest
	11, // 19: bifrost.content.v1.beacon.BeaconService.ListComments:input_type -> bifrost.content.v1.beacon.ListCommentsRequest
	13, // 20: bifrost.content.v1.beacon.BeaconService.GetUser:input_type -> bifrost.content.v1.beacon.GetUserRequest
	15, // 21: bifrost.content.v1.beacon.BeaconService.ListCategories:input_type -> bifrost.content.v1.beacon.ListCategoriesRequest
	17, // 22: bifrost.content.v1.beacon.BeaconService.ListTags:input_type -> bifrost.content.v1.beacon.ListTagsRequest
	8,  // 23: bifrost.content.v1.beacon.BeaconService.GetPost:output_type -> bifrost.content.v1.beacon.GetPostResponse
	10, // 24: bifrost.content.v1.beacon.BeaconService.ListPosts:output_type -> bifrost.content.v1.beacon.ListPostsResponse
	12, // 25: bifrost.content.v1.beacon.BeaconService.ListComments:output_type -> bifrost.content.v1.beacon.ListCommentsResponse
	14, // 26: bifrost.content.v1.beacon.BeaconService.GetUser:output_type -> bifrost.content.v1.beacon.GetUserResponse
	16, // 27: bifrost.content.v1.beacon.BeaconService.ListCategories:output_type -> bifrost.content.v1.beacon.ListCategoriesResponse
	18, // 28: bifrost.content.v1.beacon.BeaconService.ListTags:output_type -> bifrost.content.v1.beacon.ListTagsResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_content_v1_beacon_beacon_proto_init() }
func file_api_content_v1_beacon_beacon_proto_init() {
	if File_api_content_v1_beacon_beacon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_content_v1_beacon_beacon_proto_rawDesc), len(file_api_content_v1_beacon_beacon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_content_v1_beacon_beacon_proto_goTypes,
		DependencyIndexes: file_api_content_v1_beacon_beacon_proto_depIdxs,
		MessageInfos:      file_api_content_v1_beacon_beacon_proto_msgTypes,
	}.Build()
	File_api_content_v1_beacon_beacon_proto = out.File
	file_api_content_v1_beacon_beacon_proto_goTypes = nil
	file_api_content_v1_beacon_beacon_proto_depIdxs = nil
}
