// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: api/content/v1/forge/forge.proto

package forgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RenderService_RenderPreview_FullMethodName = "/bifrost.content.v1.forge.RenderService/RenderPreview"
	RenderService_GetRenderMeta_FullMethodName = "/bifrost.content.v1.forge.RenderService/GetRenderMeta"
)

// RenderServiceClient is the client API for RenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==========================================
// Forge Service: 渲染与计算核心
// ==========================================
type RenderServiceClient interface {
	// 实时预览 (无状态计算)
	// 用于编辑器：前端发 Markdown -> Forge 渲染 -> 返回 HTML，不存库
	RenderPreview(ctx context.Context, in *RenderPreviewRequest, opts ...grpc.CallOption) (*RenderPreviewResponse, error)
	// 获取渲染器元数据 (如支持的 Markdown 扩展版本)
	GetRenderMeta(ctx context.Context, in *GetRenderMetaRequest, opts ...grpc.CallOption) (*GetRenderMetaResponse, error)
}

type renderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRenderServiceClient(cc grpc.ClientConnInterface) RenderServiceClient {
	return &renderServiceClient{cc}
}

func (c *renderServiceClient) RenderPreview(ctx context.Context, in *RenderPreviewRequest, opts ...grpc.CallOption) (*RenderPreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderPreviewResponse)
	err := c.cc.Invoke(ctx, RenderService_RenderPreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *renderServiceClient) GetRenderMeta(ctx context.Context, in *GetRenderMetaRequest, opts ...grpc.CallOption) (*GetRenderMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRenderMetaResponse)
	err := c.cc.Invoke(ctx, RenderService_GetRenderMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RenderServiceServer is the server API for RenderService service.
// All implementations must embed UnimplementedRenderServiceServer
// for forward compatibility.
//
// ==========================================
// Forge Service: 渲染与计算核心
// ==========================================
type RenderServiceServer interface {
	// 实时预览 (无状态计算)
	// 用于编辑器：前端发 Markdown -> Forge 渲染 -> 返回 HTML，不存库
	RenderPreview(context.Context, *RenderPreviewRequest) (*RenderPreviewResponse, error)
	// 获取渲染器元数据 (如支持的 Markdown 扩展版本)
	GetRenderMeta(context.Context, *GetRenderMetaRequest) (*GetRenderMetaResponse, error)
	mustEmbedUnimplementedRenderServiceServer()
}

// UnimplementedRenderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRenderServiceServer struct{}

func (UnimplementedRenderServiceServer) RenderPreview(context.Context, *RenderPreviewRequest) (*RenderPreviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderPreview not implemented")
}
func (UnimplementedRenderServiceServer) GetRenderMeta(context.Context, *GetRenderMetaRequest) (*GetRenderMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRenderMeta not implemented")
}
func (UnimplementedRenderServiceServer) mustEmbedUnimplementedRenderServiceServer() {}
func (UnimplementedRenderServiceServer) testEmbeddedByValue()                       {}

// UnsafeRenderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RenderServiceServer will
// result in compilation errors.
type UnsafeRenderServiceServer interface {
	mustEmbedUnimplementedRenderServiceServer()
}

func RegisterRenderServiceServer(s grpc.ServiceRegistrar, srv RenderServiceServer) {
	// If the following call panics, it indicates UnimplementedRenderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RenderService_ServiceDesc, srv)
}

func _RenderService_RenderPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RenderServiceServer).RenderPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RenderService_RenderPreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RenderServiceServer).RenderPreview(ctx, req.(*RenderPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RenderService_GetRenderMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRenderMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RenderServiceServer).GetRenderMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RenderService_GetRenderMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RenderServiceServer).GetRenderMeta(ctx, req.(*GetRenderMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RenderService_ServiceDesc is the grpc.ServiceDesc for RenderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RenderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bifrost.content.v1.forge.RenderService",
	HandlerType: (*RenderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenderPreview",
			Handler:    _RenderService_RenderPreview_Handler,
		},
		{
			MethodName: "GetRenderMeta",
			Handler:    _RenderService_GetRenderMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/content/v1/forge/forge.proto",
}
