// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/content/v1/forge/forge.proto

package forgev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderPreviewRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RawMarkdown string                 `protobuf:"bytes,1,opt,name=raw_markdown,json=rawMarkdown,proto3" json:"raw_markdown,omitempty"`
	// 可选：指定渲染模式 (如 "article", "comment", "bio") 以应用不同的 XSS 策略
	Mode          string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderPreviewRequest) Reset() {
	*x = RenderPreviewRequest{}
	mi := &file_api_content_v1_forge_forge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPreviewRequest) ProtoMessage() {}

func (x *RenderPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_forge_forge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPreviewRequest.ProtoReflect.Descriptor instead.
func (*RenderPreviewRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_forge_forge_proto_rawDescGZIP(), []int{0}
}

func (x *RenderPreviewRequest) GetRawMarkdown() string {
	if x != nil {
		return x.RawMarkdown
	}
	return ""
}

func (x *RenderPreviewRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type RenderPreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HtmlBody      string                 `protobuf:"bytes,1,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	TocJson       string                 `protobuf:"bytes,2,opt,name=toc_json,json=tocJson,proto3" json:"toc_json,omitempty"` // 同时也生成目录结构供预览
	TookMs        float32                `protobuf:"fixed32,3,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`  // 性能监控：渲染耗时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderPreviewResponse) Reset() {
	*x = RenderPreviewResponse{}
	mi := &file_api_content_v1_forge_forge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPreviewResponse) ProtoMessage() {}

func (x *RenderPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_forge_forge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPreviewResponse.ProtoReflect.Descriptor instead.
func (*RenderPreviewResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_forge_forge_proto_rawDescGZIP(), []int{1}
}

func (x *RenderPreviewResponse) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *RenderPreviewResponse) GetTocJson() string {
	if x != nil {
		return x.TocJson
	}
	return ""
}

func (x *RenderPreviewResponse) GetTookMs() float32 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

type GetRenderMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRenderMetaRequest) Reset() {
	*x = GetRenderMetaRequest{}
	mi := &file_api_content_v1_forge_forge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRenderMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRenderMetaRequest) ProtoMessage() {}

func (x *GetRenderMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_forge_forge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRenderMetaRequest.ProtoReflect.Descriptor instead.
func (*GetRenderMetaRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_forge_forge_proto_rawDescGZIP(), []int{2}
}

type GetRenderMetaResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	EnabledExtensions []string               `protobuf:"bytes,2,rep,name=enabled_extensions,json=enabledExtensions,proto3" json:"enabled_extensions,omitempty"` // e.g. ["table", "strikethrough", "mermaid"]
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRenderMetaResponse) Reset() {
	*x = GetRenderMetaResponse{}
	mi := &file_api_content_v1_forge_forge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRenderMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRenderMetaResponse) ProtoMessage() {}

func (x *GetRenderMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_forge_forge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRenderMetaResponse.ProtoReflect.Descriptor instead.
func (*GetRenderMetaResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_forge_forge_proto_rawDescGZIP(), []int{3}
}

func (x *GetRenderMetaResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetRenderMetaResponse) GetEnabledExtensions() []string {
	if x != nil {
		return x.EnabledExtensions
	}
	return nil
}

var File_api_content_v1_forge_forge_proto protoreflect.FileDescriptor

const file_api_content_v1_forge_forge_proto_rawDesc = "" +
	"\n" +
	" api/content/v1/forge/forge.proto\x12\x18bifrost.content.v1.forge\x1a\x1cgoogle/api/annotations.proto\"M\n" +
	"\x14RenderPreviewRequest\x12!\n" +
	"\fraw_markdown\x18\x01 \x01(\tR\vrawMarkdown\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"h\n" +
	"\x15RenderPreviewResponse\x12\x1b\n" +
	"\thtml_body\x18\x01 \x01(\tR\bhtmlBody\x12\x19\n" +
	"\btoc_json\x18\x02 \x01(\tR\atocJson\x12\x17\n" +
	"\atook_ms\x18\x03 \x01(\x02R\x06tookMs\"\x16\n" +
	"\x14GetRenderMetaRequest\"`\n" +
	"\x15GetRenderMetaResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12-\n" +
	"\x12enabled_extensions\x18\x02 \x03(\tR\x11enabledExtensions2\xad\x02\n" +
	"\rRenderService\x12\x8f\x01\n" +
	"\rRenderPreview\x12..bifrost.content.v1.forge.RenderPreviewRequest\x1a/.bifrost.content.v1.forge.RenderPreviewResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/render/preview\x12\x89\x01\n" +
	"\rGetRenderMeta\x12..bifrost.content.v1.forge.GetRenderMetaRequest\x1a/.bifrost.content.v1.forge.GetRenderMetaResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/render/metaB>Z<github.com/gulugulu3399/bifrost/api/content/v1/forge;forgev1b\x06proto3"

var (
	file_api_content_v1_forge_forge_proto_rawDescOnce sync.Once
	file_api_content_v1_forge_forge_proto_rawDescData []byte
)

func file_api_content_v1_forge_forge_proto_rawDescGZIP() []byte {
	file_api_content_v1_forge_forge_proto_rawDescOnce.Do(func() {
		file_api_content_v1_forge_forge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_content_v1_forge_forge_proto_rawDesc), len(file_api_content_v1_forge_forge_proto_rawDesc)))
	})
	return file_api_content_v1_forge_forge_proto_rawDescData
}

var file_api_content_v1_forge_forge_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_content_v1_forge_forge_proto_goTypes = []any{
	(*RenderPreviewRequest)(nil),  // 0: bifrost.content.v1.forge.RenderPreviewRequest
	(*RenderPreviewResponse)(nil), // 1: bifrost.content.v1.forge.RenderPreviewResponse
	(*GetRenderMetaRequest)(nil),  // 2: bifrost.content.v1.forge.GetRenderMetaRequest
	(*GetRenderMetaResponse)(nil), // 3: bifrost.content.v1.forge.GetRenderMetaResponse
}
var file_api_content_v1_forge_forge_proto_depIdxs = []int32{
	0, // 0: bifrost.content.v1.forge.RenderService.RenderPreview:input_type -> bifrost.content.v1.forge.RenderPreviewRequest
	2, // 1: bifrost.content.v1.forge.RenderService.GetRenderMeta:input_type -> bifrost.content.v1.forge.GetRenderMetaRequest
	1, // 2: bifrost.content.v1.forge.RenderService.RenderPreview:output_type -> bifrost.content.v1.forge.RenderPreviewResponse
	3, // 3: bifrost.content.v1.forge.RenderService.GetRenderMeta:output_type -> bifrost.content.v1.forge.GetRenderMetaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_content_v1_forge_forge_proto_init() }
func file_api_content_v1_forge_forge_proto_init() {
	if File_api_content_v1_forge_forge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_content_v1_forge_forge_proto_rawDesc), len(file_api_content_v1_forge_forge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_content_v1_forge_forge_proto_goTypes,
		DependencyIndexes: file_api_content_v1_forge_forge_proto_depIdxs,
		MessageInfos:      file_api_content_v1_forge_forge_proto_msgTypes,
	}.Build()
	File_api_content_v1_forge_forge_proto = out.File
	file_api_content_v1_forge_forge_proto_goTypes = nil
	file_api_content_v1_forge_forge_proto_depIdxs = nil
}
