// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/content/v1/models.proto

package contentv1

import (
	v1 "github.com/gulugulu3399/bifrost/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文章状态
type PostStatus int32

const (
	PostStatus_POST_STATUS_UNSPECIFIED PostStatus = 0 // 默认值必须是 0
	PostStatus_POST_STATUS_DRAFT       PostStatus = 1 // 草稿
	PostStatus_POST_STATUS_PUBLISHED   PostStatus = 2 // 已发布
	PostStatus_POST_STATUS_ARCHIVED    PostStatus = 3 // 已归档
)

// Enum value maps for PostStatus.
var (
	PostStatus_name = map[int32]string{
		0: "POST_STATUS_UNSPECIFIED",
		1: "POST_STATUS_DRAFT",
		2: "POST_STATUS_PUBLISHED",
		3: "POST_STATUS_ARCHIVED",
	}
	PostStatus_value = map[string]int32{
		"POST_STATUS_UNSPECIFIED": 0,
		"POST_STATUS_DRAFT":       1,
		"POST_STATUS_PUBLISHED":   2,
		"POST_STATUS_ARCHIVED":    3,
	}
)

func (x PostStatus) Enum() *PostStatus {
	p := new(PostStatus)
	*p = x
	return p
}

func (x PostStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_content_v1_models_proto_enumTypes[0].Descriptor()
}

func (PostStatus) Type() protoreflect.EnumType {
	return &file_api_content_v1_models_proto_enumTypes[0]
}

func (x PostStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostStatus.Descriptor instead.
func (PostStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_content_v1_models_proto_rawDescGZIP(), []int{0}
}

// 文章可见性
type PostVisibility int32

const (
	PostVisibility_POST_VISIBILITY_UNSPECIFIED PostVisibility = 0
	PostVisibility_POST_VISIBILITY_PUBLIC      PostVisibility = 1 // 公开
	PostVisibility_POST_VISIBILITY_HIDDEN      PostVisibility = 2 // 隐藏 (知道链接可见)
	PostVisibility_POST_VISIBILITY_PASSWORD    PostVisibility = 3 // 密码保护
)

// Enum value maps for PostVisibility.
var (
	PostVisibility_name = map[int32]string{
		0: "POST_VISIBILITY_UNSPECIFIED",
		1: "POST_VISIBILITY_PUBLIC",
		2: "POST_VISIBILITY_HIDDEN",
		3: "POST_VISIBILITY_PASSWORD",
	}
	PostVisibility_value = map[string]int32{
		"POST_VISIBILITY_UNSPECIFIED": 0,
		"POST_VISIBILITY_PUBLIC":      1,
		"POST_VISIBILITY_HIDDEN":      2,
		"POST_VISIBILITY_PASSWORD":    3,
	}
)

func (x PostVisibility) Enum() *PostVisibility {
	p := new(PostVisibility)
	*p = x
	return p
}

func (x PostVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_api_content_v1_models_proto_enumTypes[1].Descriptor()
}

func (PostVisibility) Type() protoreflect.EnumType {
	return &file_api_content_v1_models_proto_enumTypes[1]
}

func (x PostVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostVisibility.Descriptor instead.
func (PostVisibility) EnumDescriptor() ([]byte, []int) {
	return file_api_content_v1_models_proto_rawDescGZIP(), []int{1}
}

// 评论状态
type CommentStatus int32

const (
	CommentStatus_COMMENT_STATUS_UNSPECIFIED CommentStatus = 0
	CommentStatus_COMMENT_STATUS_PENDING     CommentStatus = 1 // 待审核
	CommentStatus_COMMENT_STATUS_APPROVED    CommentStatus = 2 // 已通过
	CommentStatus_COMMENT_STATUS_SPAM        CommentStatus = 3 // 垃圾评论
)

// Enum value maps for CommentStatus.
var (
	CommentStatus_name = map[int32]string{
		0: "COMMENT_STATUS_UNSPECIFIED",
		1: "COMMENT_STATUS_PENDING",
		2: "COMMENT_STATUS_APPROVED",
		3: "COMMENT_STATUS_SPAM",
	}
	CommentStatus_value = map[string]int32{
		"COMMENT_STATUS_UNSPECIFIED": 0,
		"COMMENT_STATUS_PENDING":     1,
		"COMMENT_STATUS_APPROVED":    2,
		"COMMENT_STATUS_SPAM":        3,
	}
)

func (x CommentStatus) Enum() *CommentStatus {
	p := new(CommentStatus)
	*p = x
	return p
}

func (x CommentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_content_v1_models_proto_enumTypes[2].Descriptor()
}

func (CommentStatus) Type() protoreflect.EnumType {
	return &file_api_content_v1_models_proto_enumTypes[2]
}

func (x CommentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentStatus.Descriptor instead.
func (CommentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_content_v1_models_proto_rawDescGZIP(), []int{2}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // [修复] 确保使用 int64 (Snowflake)
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarKey     string                 `protobuf:"bytes,4,opt,name=avatar_key,json=avatarKey,proto3" json:"avatar_key,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,6,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_content_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_content_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatarKey() string {
	if x != nil {
		return x.AvatarKey
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PostCount     int32                  `protobuf:"varint,5,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_api_content_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_api_content_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetPostCount() int32 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	PostCount     int32                  `protobuf:"varint,4,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_api_content_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_api_content_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *Tag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tag) GetPostCount() int32 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	CoverImageKey string                 `protobuf:"bytes,5,opt,name=cover_image_key,json=coverImageKey,proto3" json:"cover_image_key,omitempty"`
	ResourceKey   string                 `protobuf:"bytes,19,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	// 核心内容
	RawMarkdown string         `protobuf:"bytes,6,opt,name=raw_markdown,json=rawMarkdown,proto3" json:"raw_markdown,omitempty"`
	HtmlBody    string         `protobuf:"bytes,7,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	TocJson     string         `protobuf:"bytes,20,opt,name=toc_json,json=tocJson,proto3" json:"toc_json,omitempty"`
	Status      PostStatus     `protobuf:"varint,8,opt,name=status,proto3,enum=bifrost.content.v1.PostStatus" json:"status,omitempty"`
	Visibility  PostVisibility `protobuf:"varint,9,opt,name=visibility,proto3,enum=bifrost.content.v1.PostVisibility" json:"visibility,omitempty"`
	// 关联
	Author   *User     `protobuf:"bytes,10,opt,name=author,proto3" json:"author,omitempty"`
	Category *Category `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	Tags     []*Tag    `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	// 统计
	ViewCount    int32                  `protobuf:"varint,13,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount    int32                  `protobuf:"varint,14,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount int32                  `protobuf:"varint,15,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	PublishedAt  *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 扩展数据 (JSONB)
	Meta          *v1.Meta `protobuf:"bytes,18,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_api_content_v1_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_api_content_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Post) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Post) GetCoverImageKey() string {
	if x != nil {
		return x.CoverImageKey
	}
	return ""
}

func (x *Post) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *Post) GetRawMarkdown() string {
	if x != nil {
		return x.RawMarkdown
	}
	return ""
}

func (x *Post) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *Post) GetTocJson() string {
	if x != nil {
		return x.TocJson
	}
	return ""
}

func (x *Post) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_POST_STATUS_UNSPECIFIED
}

func (x *Post) GetVisibility() PostVisibility {
	if x != nil {
		return x.Visibility
	}
	return PostVisibility_POST_VISIBILITY_UNSPECIFIED
}

func (x *Post) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Post) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Post) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Post) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Post) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Post) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Post) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Post) GetMeta() *v1.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 回复谁 (0 表示无)
	RootId        int64                  `protobuf:"varint,5,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`       // 楼层ID
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        CommentStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=bifrost.content.v1.CommentStatus" json:"status,omitempty"` // [修复] 引用上面定义的枚举
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_api_content_v1_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_api_content_v1_models_proto_rawDescGZIP(), []int{4}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Comment) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Comment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetStatus() CommentStatus {
	if x != nil {
		return x.Status
	}
	return CommentStatus_COMMENT_STATUS_UNSPECIFIED
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_content_v1_models_proto protoreflect.FileDescriptor

const file_api_content_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/content/v1/models.proto\x12\x12bifrost.content.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aapi/common/v1/common.proto\"\xd5\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_key\x18\x04 \x01(\tR\tavatarKey\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x19\n" +
	"\bis_admin\x18\x06 \x01(\bR\aisAdmin\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x83\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"post_count\x18\x05 \x01(\x05R\tpostCount\"\\\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1d\n" +
	"\n" +
	"post_count\x18\x04 \x01(\x05R\tpostCount\"\x9f\x06\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12&\n" +
	"\x0fcover_image_key\x18\x05 \x01(\tR\rcoverImageKey\x12!\n" +
	"\fresource_key\x18\x13 \x01(\tR\vresourceKey\x12!\n" +
	"\fraw_markdown\x18\x06 \x01(\tR\vrawMarkdown\x12\x1b\n" +
	"\thtml_body\x18\a \x01(\tR\bhtmlBody\x12\x19\n" +
	"\btoc_json\x18\x14 \x01(\tR\atocJson\x126\n" +
	"\x06status\x18\b \x01(\x0e2\x1e.bifrost.content.v1.PostStatusR\x06status\x12B\n" +
	"\n" +
	"visibility\x18\t \x01(\x0e2\".bifrost.content.v1.PostVisibilityR\n" +
	"visibility\x120\n" +
	"\x06author\x18\n" +
	" \x01(\v2\x18.bifrost.content.v1.UserR\x06author\x128\n" +
	"\bcategory\x18\v \x01(\v2\x1c.bifrost.content.v1.CategoryR\bcategory\x12+\n" +
	"\x04tags\x18\f \x03(\v2\x17.bifrost.content.v1.TagR\x04tags\x12\x1d\n" +
	"\n" +
	"view_count\x18\r \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\x0e \x01(\x05R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x0f \x01(\x05R\fcommentCount\x12=\n" +
	"\fpublished_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12+\n" +
	"\x04meta\x18\x12 \x01(\v2\x17.bifrost.common.v1.MetaR\x04meta\"\xa6\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12,\n" +
	"\x04user\x18\x03 \x01(\v2\x18.bifrost.content.v1.UserR\x04user\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\x12\x17\n" +
	"\aroot_id\x18\x05 \x01(\x03R\x06rootId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x129\n" +
	"\x06status\x18\a \x01(\x0e2!.bifrost.content.v1.CommentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*u\n" +
	"\n" +
	"PostStatus\x12\x1b\n" +
	"\x17POST_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11POST_STATUS_DRAFT\x10\x01\x12\x19\n" +
	"\x15POST_STATUS_PUBLISHED\x10\x02\x12\x18\n" +
	"\x14POST_STATUS_ARCHIVED\x10\x03*\x87\x01\n" +
	"\x0ePostVisibility\x12\x1f\n" +
	"\x1bPOST_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16POST_VISIBILITY_PUBLIC\x10\x01\x12\x1a\n" +
	"\x16POST_VISIBILITY_HIDDEN\x10\x02\x12\x1c\n" +
	"\x18POST_VISIBILITY_PASSWORD\x10\x03*\x81\x01\n" +
	"\rCommentStatus\x12\x1e\n" +
	"\x1aCOMMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMENT_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17COMMENT_STATUS_APPROVED\x10\x02\x12\x17\n" +
	"\x13COMMENT_STATUS_SPAM\x10\x03B:Z8github.com/gulugulu3399/bifrost/api/content/v1;contentv1b\x06proto3"

var (
	file_api_content_v1_models_proto_rawDescOnce sync.Once
	file_api_content_v1_models_proto_rawDescData []byte
)

func file_api_content_v1_models_proto_rawDescGZIP() []byte {
	file_api_content_v1_models_proto_rawDescOnce.Do(func() {
		file_api_content_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_content_v1_models_proto_rawDesc), len(file_api_content_v1_models_proto_rawDesc)))
	})
	return file_api_content_v1_models_proto_rawDescData
}

var file_api_content_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_content_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_content_v1_models_proto_goTypes = []any{
	(PostStatus)(0),               // 0: bifrost.content.v1.PostStatus
	(PostVisibility)(0),           // 1: bifrost.content.v1.PostVisibility
	(CommentStatus)(0),            // 2: bifrost.content.v1.CommentStatus
	(*User)(nil),                  // 3: bifrost.content.v1.User
	(*Category)(nil),              // 4: bifrost.content.v1.Category
	(*Tag)(nil),                   // 5: bifrost.content.v1.Tag
	(*Post)(nil),                  // 6: bifrost.content.v1.Post
	(*Comment)(nil),               // 7: bifrost.content.v1.Comment
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*v1.Meta)(nil),               // 9: bifrost.common.v1.Meta
}
var file_api_content_v1_models_proto_depIdxs = []int32{
	8,  // 0: bifrost.content.v1.User.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: bifrost.content.v1.Post.status:type_name -> bifrost.content.v1.PostStatus
	1,  // 2: bifrost.content.v1.Post.visibility:type_name -> bifrost.content.v1.PostVisibility
	3,  // 3: bifrost.content.v1.Post.author:type_name -> bifrost.content.v1.User
	4,  // 4: bifrost.content.v1.Post.category:type_name -> bifrost.content.v1.Category
	5,  // 5: bifrost.content.v1.Post.tags:type_name -> bifrost.content.v1.Tag
	8,  // 6: bifrost.content.v1.Post.published_at:type_name -> google.protobuf.Timestamp
	8,  // 7: bifrost.content.v1.Post.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 8: bifrost.content.v1.Post.meta:type_name -> bifrost.common.v1.Meta
	3,  // 9: bifrost.content.v1.Comment.user:type_name -> bifrost.content.v1.User
	2,  // 10: bifrost.content.v1.Comment.status:type_name -> bifrost.content.v1.CommentStatus
	8,  // 11: bifrost.content.v1.Comment.created_at:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_content_v1_models_proto_init() }
func file_api_content_v1_models_proto_init() {
	if File_api_content_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_content_v1_models_proto_rawDesc), len(file_api_content_v1_models_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_content_v1_models_proto_goTypes,
		DependencyIndexes: file_api_content_v1_models_proto_depIdxs,
		EnumInfos:         file_api_content_v1_models_proto_enumTypes,
		MessageInfos:      file_api_content_v1_models_proto_msgTypes,
	}.Build()
	File_api_content_v1_models_proto = out.File
	file_api_content_v1_models_proto_goTypes = nil
	file_api_content_v1_models_proto_depIdxs = nil
}
