// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/content/v1/nexus/nexus.proto

package nexusv1

import (
	v1 "github.com/gulugulu3399/bifrost/api/content/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User Messages
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{4}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarKey     string                 `protobuf:"bytes,5,opt,name=avatar_key,json=avatarKey,proto3" json:"avatar_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProfileResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetProfileResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GetProfileResponse) GetAvatarKey() string {
	if x != nil {
		return x.AvatarKey
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarKey     string                 `protobuf:"bytes,3,opt,name=avatar_key,json=avatarKey,proto3" json:"avatar_key,omitempty"`
	Theme         string                 `protobuf:"bytes,4,opt,name=theme,proto3" json:"theme,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarKey() string {
	if x != nil {
		return x.AvatarKey
	}
	return ""
}

func (x *UpdateProfileRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UpdateProfileRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Post Messages
type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	RawMarkdown   string                 `protobuf:"bytes,3,opt,name=raw_markdown,json=rawMarkdown,proto3" json:"raw_markdown,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TagNames      []string               `protobuf:"bytes,5,rep,name=tag_names,json=tagNames,proto3" json:"tag_names,omitempty"`
	Status        v1.PostStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=bifrost.content.v1.PostStatus" json:"status,omitempty"`
	CoverImageKey string                 `protobuf:"bytes,7,opt,name=cover_image_key,json=coverImageKey,proto3" json:"cover_image_key,omitempty"`
	ResourceKey   string                 `protobuf:"bytes,8,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreatePostRequest) GetRawMarkdown() string {
	if x != nil {
		return x.RawMarkdown
	}
	return ""
}

func (x *CreatePostRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreatePostRequest) GetTagNames() []string {
	if x != nil {
		return x.TagNames
	}
	return nil
}

func (x *CreatePostRequest) GetStatus() v1.PostStatus {
	if x != nil {
		return x.Status
	}
	return v1.PostStatus(0)
}

func (x *CreatePostRequest) GetCoverImageKey() string {
	if x != nil {
		return x.CoverImageKey
	}
	return ""
}

func (x *CreatePostRequest) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePostResponse) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	RawMarkdown   string                 `protobuf:"bytes,3,opt,name=raw_markdown,json=rawMarkdown,proto3" json:"raw_markdown,omitempty"`
	Status        v1.PostStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=bifrost.content.v1.PostStatus" json:"status,omitempty"`
	CoverImageKey string                 `protobuf:"bytes,5,opt,name=cover_image_key,json=coverImageKey,proto3" json:"cover_image_key,omitempty"`
	ResourceKey   string                 `protobuf:"bytes,6,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	CategoryId    int64                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TagNames      []string               `protobuf:"bytes,8,rep,name=tag_names,json=tagNames,proto3" json:"tag_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *UpdatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostRequest) GetRawMarkdown() string {
	if x != nil {
		return x.RawMarkdown
	}
	return ""
}

func (x *UpdatePostRequest) GetStatus() v1.PostStatus {
	if x != nil {
		return x.Status
	}
	return v1.PostStatus(0)
}

func (x *UpdatePostRequest) GetCoverImageKey() string {
	if x != nil {
		return x.CoverImageKey
	}
	return ""
}

func (x *UpdatePostRequest) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *UpdatePostRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdatePostRequest) GetTagNames() []string {
	if x != nil {
		return x.TagNames
	}
	return nil
}

type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePostResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{14}
}

func (x *DeletePostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{15}
}

func (x *DeletePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{16}
}

func (x *GetPostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *v1.Post               `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{17}
}

func (x *GetPostResponse) GetPost() *v1.Post {
	if x != nil {
		return x.Post
	}
	return nil
}

// [内部使用] 获取文章源码 (包含 raw_markdown, status, version)
type FetchSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSourceRequest) Reset() {
	*x = FetchSourceRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSourceRequest) ProtoMessage() {}

func (x *FetchSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSourceRequest.ProtoReflect.Descriptor instead.
func (*FetchSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{18}
}

func (x *FetchSourceRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type FetchSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	RawMarkdown   string                 `protobuf:"bytes,3,opt,name=raw_markdown,json=rawMarkdown,proto3" json:"raw_markdown,omitempty"`
	Status        v1.PostStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=bifrost.content.v1.PostStatus" json:"status,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"` // 用于乐观并发控制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSourceResponse) Reset() {
	*x = FetchSourceResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSourceResponse) ProtoMessage() {}

func (x *FetchSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSourceResponse.ProtoReflect.Descriptor instead.
func (*FetchSourceResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{19}
}

func (x *FetchSourceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FetchSourceResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FetchSourceResponse) GetRawMarkdown() string {
	if x != nil {
		return x.RawMarkdown
	}
	return ""
}

func (x *FetchSourceResponse) GetStatus() v1.PostStatus {
	if x != nil {
		return x.Status
	}
	return v1.PostStatus(0)
}

func (x *FetchSourceResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// [内部使用] 列出所有草稿和已发布文章 (管理后台用)
type ListDraftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"` // 搜标题/内容
	CategoryId    int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Status        v1.PostStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=bifrost.content.v1.PostStatus" json:"status,omitempty"` // 可筛选状态 (DRAFT, PUBLISHED, ARCHIVED)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDraftsRequest) Reset() {
	*x = ListDraftsRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDraftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDraftsRequest) ProtoMessage() {}

func (x *ListDraftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDraftsRequest.ProtoReflect.Descriptor instead.
func (*ListDraftsRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{20}
}

func (x *ListDraftsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDraftsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDraftsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListDraftsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListDraftsRequest) GetStatus() v1.PostStatus {
	if x != nil {
		return x.Status
	}
	return v1.PostStatus(0)
}

type ListDraftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*v1.Post             `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"` // 直接返回完整 Model
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDraftsResponse) Reset() {
	*x = ListDraftsResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDraftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDraftsResponse) ProtoMessage() {}

func (x *ListDraftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDraftsResponse.ProtoReflect.Descriptor instead.
func (*ListDraftsResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{21}
}

func (x *ListDraftsResponse) GetPosts() []*v1.Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListDraftsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 请求定义 (兼容旧的 ListPosts，但已重命名为 ListDrafts)
type ListPostsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Page     int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 管理端筛选器
	Keyword       string        `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"` // 搜标题/内容
	CategoryId    int64         `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Status        v1.PostStatus `protobuf:"varint,5,opt,name=status,proto3,enum=bifrost.content.v1.PostStatus" json:"status,omitempty"` // 管理员可以搜 "DRAFT"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest) Reset() {
	*x = ListPostsRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest) ProtoMessage() {}

func (x *ListPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest.ProtoReflect.Descriptor instead.
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{22}
}

func (x *ListPostsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPostsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPostsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListPostsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListPostsRequest) GetStatus() v1.PostStatus {
	if x != nil {
		return x.Status
	}
	return v1.PostStatus(0)
}

type ListPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*v1.Post             `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"` // 直接返回完整 Model
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsResponse) Reset() {
	*x = ListPostsResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsResponse) ProtoMessage() {}

func (x *ListPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsResponse.ProtoReflect.Descriptor instead.
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{23}
}

func (x *ListPostsResponse) GetPosts() []*v1.Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListPostsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Comment Messages
type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{24}
}

func (x *CreateCommentRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateCommentRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Status        v1.CommentStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=bifrost.content.v1.CommentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{25}
}

func (x *CreateCommentResponse) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CreateCommentResponse) GetStatus() v1.CommentStatus {
	if x != nil {
		return x.Status
	}
	return v1.CommentStatus(0)
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteTagRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteTagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Category Messages
type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{30}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{31}
}

func (x *CreateCategoryResponse) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateCategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteCategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{36}
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*v1.Category         `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{37}
}

func (x *ListCategoriesResponse) GetCategories() []*v1.Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

// UploadTicket Messages
type GetUploadTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"` // 原始文件名 (如 "avatar.png")
	Usage         string                 `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`       // 用途: "avatar", "cover", "post_image"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadTicketRequest) Reset() {
	*x = GetUploadTicketRequest{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadTicketRequest) ProtoMessage() {}

func (x *GetUploadTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadTicketRequest.ProtoReflect.Descriptor instead.
func (*GetUploadTicketRequest) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{38}
}

func (x *GetUploadTicketRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetUploadTicketRequest) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

type GetUploadTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // MinIO 预签名上传链接 (带 Token)
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"` // 最终的文件路径 (存库用)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadTicketResponse) Reset() {
	*x = GetUploadTicketResponse{}
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadTicketResponse) ProtoMessage() {}

func (x *GetUploadTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_nexus_nexus_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadTicketResponse.ProtoReflect.Descriptor instead.
func (*GetUploadTicketResponse) Descriptor() ([]byte, []int) {
	return file_api_content_v1_nexus_nexus_proto_rawDescGZIP(), []int{39}
}

func (x *GetUploadTicketResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUploadTicketResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

var File_api_content_v1_nexus_nexus_proto protoreflect.FileDescriptor

const file_api_content_v1_nexus_nexus_proto_rawDesc = "" +
	"\n" +
	" api/content/v1/nexus/nexus.proto\x12\x18bifrost.content.v1.nexus\x1a\x1bapi/content/v1/models.proto\x1a\x1cgoogle/api/annotations.proto\"{\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"J\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"v\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"]\n" +
	"\x15ChangePasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"2\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x96\x01\n" +
	"\x12GetProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_key\x18\x05 \x01(\tR\tavatarKey\"\x95\x01\n" +
	"\x14UpdateProfileRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_key\x18\x03 \x01(\tR\tavatarKey\x12\x14\n" +
	"\x05theme\x18\x04 \x01(\tR\x05theme\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"1\n" +
	"\x15UpdateProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa1\x02\n" +
	"\x11CreatePostRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12!\n" +
	"\fraw_markdown\x18\x03 \x01(\tR\vrawMarkdown\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12\x1b\n" +
	"\ttag_names\x18\x05 \x03(\tR\btagNames\x126\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1e.bifrost.content.v1.PostStatusR\x06status\x12&\n" +
	"\x0fcover_image_key\x18\a \x01(\tR\rcoverImageKey\x12!\n" +
	"\fresource_key\x18\b \x01(\tR\vresourceKey\"-\n" +
	"\x12CreatePostResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"\xa6\x02\n" +
	"\x11UpdatePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fraw_markdown\x18\x03 \x01(\tR\vrawMarkdown\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.bifrost.content.v1.PostStatusR\x06status\x12&\n" +
	"\x0fcover_image_key\x18\x05 \x01(\tR\rcoverImageKey\x12!\n" +
	"\fresource_key\x18\x06 \x01(\tR\vresourceKey\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x03R\n" +
	"categoryId\x12\x1b\n" +
	"\ttag_names\x18\b \x03(\tR\btagNames\".\n" +
	"\x12UpdatePostResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\",\n" +
	"\x11DeletePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\".\n" +
	"\x12DeletePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x0eGetPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"?\n" +
	"\x0fGetPostResponse\x12,\n" +
	"\x04post\x18\x01 \x01(\v2\x18.bifrost.content.v1.PostR\x04post\"-\n" +
	"\x12FetchSourceRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"\xb0\x01\n" +
	"\x13FetchSourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fraw_markdown\x18\x03 \x01(\tR\vrawMarkdown\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.bifrost.content.v1.PostStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"\xb7\x01\n" +
	"\x11ListDraftsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x126\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1e.bifrost.content.v1.PostStatusR\x06status\"e\n" +
	"\x12ListDraftsResponse\x12.\n" +
	"\x05posts\x18\x01 \x03(\v2\x18.bifrost.content.v1.PostR\x05posts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xb6\x01\n" +
	"\x10ListPostsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x126\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1e.bifrost.content.v1.PostStatusR\x06status\"d\n" +
	"\x11ListPostsResponse\x12.\n" +
	"\x05posts\x18\x01 \x03(\v2\x18.bifrost.content.v1.PostR\x05posts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"f\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"q\n" +
	"\x15CreateCommentResponse\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.bifrost.content.v1.CommentStatusR\x06status\"5\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x10DeleteTagRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x03R\x05tagId\"-\n" +
	"\x11DeleteTagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"9\n" +
	"\x16CreateCategoryResponse\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\"\x82\x01\n" +
	"\x15UpdateCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"2\n" +
	"\x16UpdateCategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x15DeleteCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\"2\n" +
	"\x16DeleteCategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x17\n" +
	"\x15ListCategoriesRequest\"V\n" +
	"\x16ListCategoriesResponse\x12<\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1c.bifrost.content.v1.CategoryR\n" +
	"categories\"J\n" +
	"\x16GetUploadTicketRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x14\n" +
	"\x05usage\x18\x02 \x01(\tR\x05usage\"W\n" +
	"\x17GetUploadTicketResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey2\xae\x05\n" +
	"\vUserService\x12\x7f\n" +
	"\bRegister\x12).bifrost.content.v1.nexus.RegisterRequest\x1a*.bifrost.content.v1.nexus.RegisterResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12s\n" +
	"\x05Login\x12&.bifrost.content.v1.nexus.LoginRequest\x1a'.bifrost.content.v1.nexus.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12\x92\x01\n" +
	"\x0eChangePassword\x12/.bifrost.content.v1.nexus.ChangePasswordRequest\x1a0.bifrost.content.v1.nexus.ChangePasswordResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/users/password\x12\x82\x01\n" +
	"\n" +
	"GetProfile\x12+.bifrost.content.v1.nexus.GetProfileRequest\x1a,.bifrost.content.v1.nexus.GetProfileResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/users/profile\x12\x8e\x01\n" +
	"\rUpdateProfile\x12..bifrost.content.v1.nexus.UpdateProfileRequest\x1a/.bifrost.content.v1.nexus.UpdateProfileResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/users/profile2\xc8\x06\n" +
	"\vPostService\x12{\n" +
	"\n" +
	"ListDrafts\x12+.bifrost.content.v1.nexus.ListDraftsRequest\x1a,.bifrost.content.v1.nexus.ListDraftsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/drafts\x12\x94\x01\n" +
	"\vFetchSource\x12,.bifrost.content.v1.nexus.FetchSourceRequest\x1a-.bifrost.content.v1.nexus.FetchSourceResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/admin/posts/{post_id}/source\x12\x83\x01\n" +
	"\n" +
	"CreatePost\x12+.bifrost.content.v1.nexus.CreatePostRequest\x1a,.bifrost.content.v1.nexus.CreatePostResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/admin/posts\x12\x8d\x01\n" +
	"\n" +
	"UpdatePost\x12+.bifrost.content.v1.nexus.UpdatePostRequest\x1a,.bifrost.content.v1.nexus.UpdatePostResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/v1/admin/posts/{post_id}\x12\x8a\x01\n" +
	"\n" +
	"DeletePost\x12+.bifrost.content.v1.nexus.DeletePostRequest\x1a,.bifrost.content.v1.nexus.DeletePostResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/admin/posts/{post_id}\x12\x81\x01\n" +
	"\aGetPost\x12(.bifrost.content.v1.nexus.GetPostRequest\x1a).bifrost.content.v1.nexus.GetPostResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/admin/posts/{post_id}2\xc2\x02\n" +
	"\x0eCommentService\x12\x99\x01\n" +
	"\rCreateComment\x12..bifrost.content.v1.nexus.CreateCommentRequest\x1a/.bifrost.content.v1.nexus.CreateCommentResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/posts/{post_id}/comments\x12\x93\x01\n" +
	"\rDeleteComment\x12..bifrost.content.v1.nexus.DeleteCommentRequest\x1a/.bifrost.content.v1.nexus.DeleteCommentResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/comments/{comment_id}2\x8d\x01\n" +
	"\n" +
	"TagService\x12\x7f\n" +
	"\tDeleteTag\x12*.bifrost.content.v1.nexus.DeleteTagRequest\x1a+.bifrost.content.v1.nexus.DeleteTagResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/tags/{tag_id}2\xeb\x04\n" +
	"\x0fCategoryService\x12\x8e\x01\n" +
	"\x0eCreateCategory\x12/.bifrost.content.v1.nexus.CreateCategoryRequest\x1a0.bifrost.content.v1.nexus.CreateCategoryResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/categories\x12\x9c\x01\n" +
	"\x0eUpdateCategory\x12/.bifrost.content.v1.nexus.UpdateCategoryRequest\x1a0.bifrost.content.v1.nexus.UpdateCategoryResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/v1/categories/{category_id}\x12\x99\x01\n" +
	"\x0eDeleteCategory\x12/.bifrost.content.v1.nexus.DeleteCategoryRequest\x1a0.bifrost.content.v1.nexus.DeleteCategoryResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/v1/categories/{category_id}\x12\x8b\x01\n" +
	"\x0eListCategories\x12/.bifrost.content.v1.nexus.ListCategoriesRequest\x1a0.bifrost.content.v1.nexus.ListCategoriesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/categories2\xaf\x01\n" +
	"\x0eStorageService\x12\x9c\x01\n" +
	"\x0fGetUploadTicket\x120.bifrost.content.v1.nexus.GetUploadTicketRequest\x1a1.bifrost.content.v1.nexus.GetUploadTicketResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/storage/upload_ticketB>Z<github.com/gulugulu3399/bifrost/api/content/v1/nexus;nexusv1b\x06proto3"

var (
	file_api_content_v1_nexus_nexus_proto_rawDescOnce sync.Once
	file_api_content_v1_nexus_nexus_proto_rawDescData []byte
)

func file_api_content_v1_nexus_nexus_proto_rawDescGZIP() []byte {
	file_api_content_v1_nexus_nexus_proto_rawDescOnce.Do(func() {
		file_api_content_v1_nexus_nexus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_content_v1_nexus_nexus_proto_rawDesc), len(file_api_content_v1_nexus_nexus_proto_rawDesc)))
	})
	return file_api_content_v1_nexus_nexus_proto_rawDescData
}

var file_api_content_v1_nexus_nexus_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_api_content_v1_nexus_nexus_proto_goTypes = []any{
	(*RegisterRequest)(nil),         // 0: bifrost.content.v1.nexus.RegisterRequest
	(*RegisterResponse)(nil),        // 1: bifrost.content.v1.nexus.RegisterResponse
	(*LoginRequest)(nil),            // 2: bifrost.content.v1.nexus.LoginRequest
	(*LoginResponse)(nil),           // 3: bifrost.content.v1.nexus.LoginResponse
	(*ChangePasswordRequest)(nil),   // 4: bifrost.content.v1.nexus.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),  // 5: bifrost.content.v1.nexus.ChangePasswordResponse
	(*GetProfileRequest)(nil),       // 6: bifrost.content.v1.nexus.GetProfileRequest
	(*GetProfileResponse)(nil),      // 7: bifrost.content.v1.nexus.GetProfileResponse
	(*UpdateProfileRequest)(nil),    // 8: bifrost.content.v1.nexus.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),   // 9: bifrost.content.v1.nexus.UpdateProfileResponse
	(*CreatePostRequest)(nil),       // 10: bifrost.content.v1.nexus.CreatePostRequest
	(*CreatePostResponse)(nil),      // 11: bifrost.content.v1.nexus.CreatePostResponse
	(*UpdatePostRequest)(nil),       // 12: bifrost.content.v1.nexus.UpdatePostRequest
	(*UpdatePostResponse)(nil),      // 13: bifrost.content.v1.nexus.UpdatePostResponse
	(*DeletePostRequest)(nil),       // 14: bifrost.content.v1.nexus.DeletePostRequest
	(*DeletePostResponse)(nil),      // 15: bifrost.content.v1.nexus.DeletePostResponse
	(*GetPostRequest)(nil),          // 16: bifrost.content.v1.nexus.GetPostRequest
	(*GetPostResponse)(nil),         // 17: bifrost.content.v1.nexus.GetPostResponse
	(*FetchSourceRequest)(nil),      // 18: bifrost.content.v1.nexus.FetchSourceRequest
	(*FetchSourceResponse)(nil),     // 19: bifrost.content.v1.nexus.FetchSourceResponse
	(*ListDraftsRequest)(nil),       // 20: bifrost.content.v1.nexus.ListDraftsRequest
	(*ListDraftsResponse)(nil),      // 21: bifrost.content.v1.nexus.ListDraftsResponse
	(*ListPostsRequest)(nil),        // 22: bifrost.content.v1.nexus.ListPostsRequest
	(*ListPostsResponse)(nil),       // 23: bifrost.content.v1.nexus.ListPostsResponse
	(*CreateCommentRequest)(nil),    // 24: bifrost.content.v1.nexus.CreateCommentRequest
	(*CreateCommentResponse)(nil),   // 25: bifrost.content.v1.nexus.CreateCommentResponse
	(*DeleteCommentRequest)(nil),    // 26: bifrost.content.v1.nexus.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),   // 27: bifrost.content.v1.nexus.DeleteCommentResponse
	(*DeleteTagRequest)(nil),        // 28: bifrost.content.v1.nexus.DeleteTagRequest
	(*DeleteTagResponse)(nil),       // 29: bifrost.content.v1.nexus.DeleteTagResponse
	(*CreateCategoryRequest)(nil),   // 30: bifrost.content.v1.nexus.CreateCategoryRequest
	(*CreateCategoryResponse)(nil),  // 31: bifrost.content.v1.nexus.CreateCategoryResponse
	(*UpdateCategoryRequest)(nil),   // 32: bifrost.content.v1.nexus.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil),  // 33: bifrost.content.v1.nexus.UpdateCategoryResponse
	(*DeleteCategoryRequest)(nil),   // 34: bifrost.content.v1.nexus.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil),  // 35: bifrost.content.v1.nexus.DeleteCategoryResponse
	(*ListCategoriesRequest)(nil),   // 36: bifrost.content.v1.nexus.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),  // 37: bifrost.content.v1.nexus.ListCategoriesResponse
	(*GetUploadTicketRequest)(nil),  // 38: bifrost.content.v1.nexus.GetUploadTicketRequest
	(*GetUploadTicketResponse)(nil), // 39: bifrost.content.v1.nexus.GetUploadTicketResponse
	(v1.PostStatus)(0),              // 40: bifrost.content.v1.PostStatus
	(*v1.Post)(nil),                 // 41: bifrost.content.v1.Post
	(v1.CommentStatus)(0),           // 42: bifrost.content.v1.CommentStatus
	(*v1.Category)(nil),             // 43: bifrost.content.v1.Category
}
var file_api_content_v1_nexus_nexus_proto_depIdxs = []int32{
	40, // 0: bifrost.content.v1.nexus.CreatePostRequest.status:type_name -> bifrost.content.v1.PostStatus
	40, // 1: bifrost.content.v1.nexus.UpdatePostRequest.status:type_name -> bifrost.content.v1.PostStatus
	41, // 2: bifrost.content.v1.nexus.GetPostResponse.post:type_name -> bifrost.content.v1.Post
	40, // 3: bifrost.content.v1.nexus.FetchSourceResponse.status:type_name -> bifrost.content.v1.PostStatus
	40, // 4: bifrost.content.v1.nexus.ListDraftsRequest.status:type_name -> bifrost.content.v1.PostStatus
	41, // 5: bifrost.content.v1.nexus.ListDraftsResponse.posts:type_name -> bifrost.content.v1.Post
	40, // 6: bifrost.content.v1.nexus.ListPostsRequest.status:type_name -> bifrost.content.v1.PostStatus
	41, // 7: bifrost.content.v1.nexus.ListPostsResponse.posts:type_name -> bifrost.content.v1.Post
	42, // 8: bifrost.content.v1.nexus.CreateCommentResponse.status:type_name -> bifrost.content.v1.CommentStatus
	43, // 9: bifrost.content.v1.nexus.ListCategoriesResponse.categories:type_name -> bifrost.content.v1.Category
	0,  // 10: bifrost.content.v1.nexus.UserService.Register:input_type -> bifrost.content.v1.nexus.RegisterRequest
	2,  // 11: bifrost.content.v1.nexus.UserService.Login:input_type -> bifrost.content.v1.nexus.LoginRequest
	4,  // 12: bifrost.content.v1.nexus.UserService.ChangePassword:input_type -> bifrost.content.v1.nexus.ChangePasswordRequest
	6,  // 13: bifrost.content.v1.nexus.UserService.GetProfile:input_type -> bifrost.content.v1.nexus.GetProfileRequest
	8,  // 14: bifrost.content.v1.nexus.UserService.UpdateProfile:input_type -> bifrost.content.v1.nexus.UpdateProfileRequest
	20, // 15: bifrost.content.v1.nexus.PostService.ListDrafts:input_type -> bifrost.content.v1.nexus.ListDraftsRequest
	18, // 16: bifrost.content.v1.nexus.PostService.FetchSource:input_type -> bifrost.content.v1.nexus.FetchSourceRequest
	10, // 17: bifrost.content.v1.nexus.PostService.CreatePost:input_type -> bifrost.content.v1.nexus.CreatePostRequest
	12, // 18: bifrost.content.v1.nexus.PostService.UpdatePost:input_type -> bifrost.content.v1.nexus.UpdatePostRequest
	14, // 19: bifrost.content.v1.nexus.PostService.DeletePost:input_type -> bifrost.content.v1.nexus.DeletePostRequest
	16, // 20: bifrost.content.v1.nexus.PostService.GetPost:input_type -> bifrost.content.v1.nexus.GetPostRequest
	24, // 21: bifrost.content.v1.nexus.CommentService.CreateComment:input_type -> bifrost.content.v1.nexus.CreateCommentRequest
	26, // 22: bifrost.content.v1.nexus.CommentService.DeleteComment:input_type -> bifrost.content.v1.nexus.DeleteCommentRequest
	28, // 23: bifrost.content.v1.nexus.TagService.DeleteTag:input_type -> bifrost.content.v1.nexus.DeleteTagRequest
	30, // 24: bifrost.content.v1.nexus.CategoryService.CreateCategory:input_type -> bifrost.content.v1.nexus.CreateCategoryRequest
	32, // 25: bifrost.content.v1.nexus.CategoryService.UpdateCategory:input_type -> bifrost.content.v1.nexus.UpdateCategoryRequest
	34, // 26: bifrost.content.v1.nexus.CategoryService.DeleteCategory:input_type -> bifrost.content.v1.nexus.DeleteCategoryRequest
	36, // 27: bifrost.content.v1.nexus.CategoryService.ListCategories:input_type -> bifrost.content.v1.nexus.ListCategoriesRequest
	38, // 28: bifrost.content.v1.nexus.StorageService.GetUploadTicket:input_type -> bifrost.content.v1.nexus.GetUploadTicketRequest
	1,  // 29: bifrost.content.v1.nexus.UserService.Register:output_type -> bifrost.content.v1.nexus.RegisterResponse
	3,  // 30: bifrost.content.v1.nexus.UserService.Login:output_type -> bifrost.content.v1.nexus.LoginResponse
	5,  // 31: bifrost.content.v1.nexus.UserService.ChangePassword:output_type -> bifrost.content.v1.nexus.ChangePasswordResponse
	7,  // 32: bifrost.content.v1.nexus.UserService.GetProfile:output_type -> bifrost.content.v1.nexus.GetProfileResponse
	9,  // 33: bifrost.content.v1.nexus.UserService.UpdateProfile:output_type -> bifrost.content.v1.nexus.UpdateProfileResponse
	21, // 34: bifrost.content.v1.nexus.PostService.ListDrafts:output_type -> bifrost.content.v1.nexus.ListDraftsResponse
	19, // 35: bifrost.content.v1.nexus.PostService.FetchSource:output_type -> bifrost.content.v1.nexus.FetchSourceResponse
	11, // 36: bifrost.content.v1.nexus.PostService.CreatePost:output_type -> bifrost.content.v1.nexus.CreatePostResponse
	13, // 37: bifrost.content.v1.nexus.PostService.UpdatePost:output_type -> bifrost.content.v1.nexus.UpdatePostResponse
	15, // 38: bifrost.content.v1.nexus.PostService.DeletePost:output_type -> bifrost.content.v1.nexus.DeletePostResponse
	17, // 39: bifrost.content.v1.nexus.PostService.GetPost:output_type -> bifrost.content.v1.nexus.GetPostResponse
	25, // 40: bifrost.content.v1.nexus.CommentService.CreateComment:output_type -> bifrost.content.v1.nexus.CreateCommentResponse
	27, // 41: bifrost.content.v1.nexus.CommentService.DeleteComment:output_type -> bifrost.content.v1.nexus.DeleteCommentResponse
	29, // 42: bifrost.content.v1.nexus.TagService.DeleteTag:output_type -> bifrost.content.v1.nexus.DeleteTagResponse
	31, // 43: bifrost.content.v1.nexus.CategoryService.CreateCategory:output_type -> bifrost.content.v1.nexus.CreateCategoryResponse
	33, // 44: bifrost.content.v1.nexus.CategoryService.UpdateCategory:output_type -> bifrost.content.v1.nexus.UpdateCategoryResponse
	35, // 45: bifrost.content.v1.nexus.CategoryService.DeleteCategory:output_type -> bifrost.content.v1.nexus.DeleteCategoryResponse
	37, // 46: bifrost.content.v1.nexus.CategoryService.ListCategories:output_type -> bifrost.content.v1.nexus.ListCategoriesResponse
	39, // 47: bifrost.content.v1.nexus.StorageService.GetUploadTicket:output_type -> bifrost.content.v1.nexus.GetUploadTicketResponse
	29, // [29:48] is the sub-list for method output_type
	10, // [10:29] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_content_v1_nexus_nexus_proto_init() }
func file_api_content_v1_nexus_nexus_proto_init() {
	if File_api_content_v1_nexus_nexus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_content_v1_nexus_nexus_proto_rawDesc), len(file_api_content_v1_nexus_nexus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_api_content_v1_nexus_nexus_proto_goTypes,
		DependencyIndexes: file_api_content_v1_nexus_nexus_proto_depIdxs,
		MessageInfos:      file_api_content_v1_nexus_nexus_proto_msgTypes,
	}.Build()
	File_api_content_v1_nexus_nexus_proto = out.File
	file_api_content_v1_nexus_nexus_proto_goTypes = nil
	file_api_content_v1_nexus_nexus_proto_depIdxs = nil
}
